/*
 nehan3.js
 Copyright (C) 2011, 2012, Watanabe Masaki<lambda.watanabe[at]gmail.com>

 licenced under MIT licence.

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/

var Nehan3;Nehan3||(Nehan3={});
(function(){var k={debug:false,layout:{minFontSize:10,minKerningFontSize:12,defFontSize:18,tabLength:4,defLeadingRate:1.8,rubySizeRate:0.5,captionSizeRate:0.65,captionMarginRate:1,blockMarginRate:0.8,readerBorder:1,acceptableResizeRate:0.6,header:[{scale:2.4},{scale:2},{scale:1.6},{scale:1.4},{scale:1},{scale:1}],indent:{indentBefore:2,indentAfter:1},blockquote:{indentBefore:2,indentAfter:1,fontSizeRate:0.9,border:1},fieldset:{indentBefore:1,indentAfter:0,fontSizeRate:0.9,border:1},textset:{tpart:{fontSizeRate:0.9}},
dl:{indentBefore:0,indentAfter:0,dt:{indentBefore:0,indentAfter:0,fontSizeRate:0.9},dd:{indentBefore:1,indentAfter:0,fontSizeRate:0.9}},ul:{indentBefore:1,indentAfter:1,listMark:"\u30fb",li:{fontSizeRate:0.9}},ol:{indentBefore:1,indentAfter:1,listMark:"\u30fb",li:{fontSizeRate:0.9}},scenario:{shead:{size:100,fontSizeRate:0.9},sfoot:{size:80,fontSizeRate:0.7},sbody:{fontSizeRate:1,marginRate:0.2}}},color:{defCharImgColor:"000000",labelCharImgColor:"FFFFFF"},className:{img:"nehan3-img",line:"nehan3-line",
page:"nehan3-page",wrap:"nehan3-wrap",charImg:"nehan3-char-img",charIcon:"nehan3-char-icon",forkedPage:"nehan3-forked-page",alignedPage:"nehan3-aligned-page",inlineReader:"nehan3-inline-reader",inlineBox:"nehan3-inline-box",errorMsg:"nehan3-error-msg",textLine:"nehan3-text-line",rubyLine:"nehan3-ruby-line",labelLine:"nehan3-label-line",labelLineBody:"nehan3-label-line-body",rubyText:"nehan3-ruby-text",caption:"nehan3-caption",blockElement:"nehan3-block-element",tocLink:"nehan3-toc-link",header:"nehan3-header"},
rex:{word:/[\w!\.\?\/\_:#;"',]+/,nvAttr:/(?:\S+)=["']?(?:(?:.(?!["']?\s+(?:\S+)=|["']))+.)["']?/g},tags:{single:["img","br","end-page"],tcy:["pack","tcy"],greedy:["pre"],block:"img,table,iframe,ibox,textarea,ireader,ipage".split(","),fork:"blockquote,ul,ol,li,dl,dt,dd,fieldset,indent,textset,scenario".split(","),toc:["part","chapter","section","subsection"],content:"blockquote,indent,table,textarea,iframe,ibox,ipage,ireader,shead,sbody,sfoot,tpart,fieldset,ul,ol,li,dl,dt,dd".split(",")},types:{textToken:["char",
"tcy","word","rb"]},system:{lang:"ja-jp",nobr:false,conv_br:false,lexingBufferLen:2E3,enableYakuMetricsCheck:true,lineBreakCheckLevel:2},charImgRoot:"http://nehan.googlecode.com/hg/char-img"},G={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(c){for(var a=0;a<c.length;a++){var f=
c[a].string,j=c[a].prop;this.versionSearchString=c[a].versionSearch||c[a].identity;if(f){if(f.indexOf(c[a].subString)!=-1)return c[a].identity}else if(j)return c[a].identity}},searchVersion:function(c){var a=c.indexOf(this.versionSearchString);return a==-1?void 0:parseFloat(c.substring(a+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,
subString:"Apple",identity:"Safari",versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},
{string:navigator.userAgent,subString:"Gecko",identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};G.init();var t={init:function(){var c=G.browser.toLowerCase(),
a=G.OS.toLowerCase(),f=navigator.userAgent;this.isIE=c=="explorer";this.isWin=a=="windows";this.isMac=a=="mac";this.isIPhone=navigator.platform=="iPhone";this.isIPad=navigator.platform=="iPad";this.isIPod=navigator.platform=="iPod";this.isMobileSafari=this.isIPhone||this.isIPad||this.isIPod;this.isAndroid=/android/.test(f)}};t.init();var H=function(c){k.debug&&!t.isIE&&console.log(c)},q={clone:function(c){var a;if(typeof c=="object")if(c instanceof Array){a=[];for(var f=0,j=c.length;f<j;f++)a[f]=
this.clone(c[f])}else for(prop in a={},c)a[prop]=this.clone(c[prop]);else a=c;return a},cutQuote:function(c){return c.replace(/\"/g,"").replace(/\'/g,"")},cutTagHeadSpace:function(c){return c.replace(/[\s]+</g,"<")},cutHeadSpace:function(c){return c.replace(/^[\s]+/,"")},cutTailSpace:function(c){return c.replace(/[\s]+$/g,"")},cutEdgeSpace:function(c){return this.cutTailSpace(this.cutHeadSpace(c))},cutHeadCRLF:function(c){return c.replace(/^\n+/g,"")},cutTailCRLF:function(c){return c.replace(/\n+$/g,
"")},cutEdgeCRLF:function(c){return this.cutTailCRLF(this.cutHeadCRLF(c))},escape:function(c){return c.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/'/g,"&#039;").replace(/"/g,"&quot;")},filenameConcat:function(c,a){c=c==""?"":c.slice(-1)=="/"?c:c+"/";a=a==""?"":a[0]=="/"?a.substring(1,a.length):a;return c+a}},u={eq:function(c){return function(a){return c==a}},onkeypress:function(c){return function(a){c(t.isIE?event.keyCode:a.keyCode||a.which)}}},s={copy:function(c,a){for(prop in a)c[prop]=
a[prop];return c},init:function(c,a,f){for(prop in a)c[prop]=typeof f[prop]=="undefined"?a[prop]:f[prop];return c}},l={iter:function(c,a){for(var f=0,j=c.length;f<j;f++)a(c[f])},iteri:function(c,a){for(var f=0,j=c.length;f<j;f++)a(f,c[f])},map:function(c,a){for(var f=[],j=0,g=c.length;j<g;j++)f.push(a(c[j]));return f},fold:function(c,a,f){for(var j=0,g=c.length;j<g;j++)a=f(a,c[j]);return a},filter:function(c,a){for(var f=[],j=0,g=c.length;j<g;j++){var d=c[j];a(d)&&f.push(d)}return f},find:function(c,
a){for(var f=0,j=c.length;f<j;f++){var g=c[f];if(a(g))return g}return null},exists:function(c,a){for(var f=0,j=c.length;f<j;f++)if(a(c[f]))return true;return false},sum:function(c){return this.fold(c,0,function(a,c){return a+c})}},p={html:function(c){var a=[];for(prop in c)if(c[prop]){var f=c[prop]+"",f=q.escape(f);a.push(prop+"='"+f+"'")}return a==[]?"":a.join(" ")},css:function(c){var a=[];for(prop in c){var f=c[prop]+"",f=q.escape(f);a.push(prop+":"+f+";")}return a.join("")}},m={isStartTagName:function(c){return c.charAt(0)!=
"/"},isTcyTagName:function(c){return l.exists(k.tags.tcy,u.eq(c))},isSingleTagName:function(c){return l.exists(k.tags.single,u.eq(c))},isBlockTagName:function(c){return l.exists(k.tags.block,u.eq(c))},isForkPageTagName:function(c){return l.exists(k.tags.fork,u.eq(c))},isContentTagName:function(c){return l.exists(k.tags.content,u.eq(c))},start:function(c,a){var f="<"+c;if(typeof a!="undefined"||a==null)var j=p.html(a),f=j!=""?[f,j].join(" "):f;f+=this.isSingleTagName(c)?" />":">";return f},wrap:function(c,
a,f){return[this.start(c,a),f,"</"+c+">"].join("")},end:function(c){return"</"+c+">"}},w={isCharCountableToken:function(c){return!this.isTextToken(c)?false:/\s/.test(c.data)?false:c.type=="char"&&c.img?false:true},isEndPageToken:function(c){return c.type=="tag"&&c.data.name=="end-page"},isTextToken:function(c){return l.exists(k.types.textToken,u.eq(c.type))},isBlockToken:function(c){return c.type!="tag"?false:m.isBlockTagName(c.data.name)},isForkPageToken:function(c){return c.type!="tag"?false:m.isForkPageTagName(c.data.name)}},
L={isTcy:function(c){return c.length!=2?false:c=="!!"||c=="!?"||c=="??"?true:c.match(/\d\d/)!=null}},r={isHeadNg:function(c){return/[\uff09\)\u300d\u3011\u3015\uff3d\]\u3002\u300f\uff1e\u3009\u300b\u3001\uff0e\.,\u201d\u301f]/.test(c)},isTailNg:function(c){return/[\uff08\(\u300c\u3010\uff3b\u3014\u300e\uff1c\u3008\u300a\u201c\u301d]/.test(c)},isTailConnectiveChar:function(c){return/[\u3001\u3002\.\uff0e,\uff0c\u300d\u300f\uff09]/.test(c)},isKakkoStartChar:function(c){return/[\uff62\u300c\u300e\u3010\uff3b\uff08\u300a\u3008\u226a\uff1c\uff5b{\[\(]/.test(c)},
isKakkoEndChar:function(c){return/[\u300d\uff63\u300f\u3011\uff3d\uff09\u300b\u3009\u226b\uff1e\uff5d}\]\)]/.test(c)},isKutenTouten:function(c){return/[\u3001\u3002,.]/.test(c)},isZenkaku:function(c){return escape(c).charAt(1)=="u"},isHankaku:function(c){return!this.isZenkaku(c)},isSmallKana:function(c){c=c.charCodeAt(0);return l.exists([12353,12355,12357,12359,12361,12387,12419,12421,12423,12430,12449,12451,12453,12455,12457,12483,12515,12517,12519,12526,12533,12534],u.eq(c))},ofImgSrc:function(c,
a){a=typeof a!="undefined"?a:k.color.defCharImgColor;return q.filenameConcat(k.charImgRoot,c+"/"+a+".png")}},S={getLevel:function(c){for(var a=k.tags.toc,f=0,j=a.length;f<j;f++)if(a[f]==c)return f;return 0}},M={RG:[0,36,73,109,146,182,219,255],B:[0,85,170,255],namedColors:{black:{r:0,g:0,b:0},red:{r:256,g:0,b:0},green:{r:0,g:256,b:0},blue:{r:0,g:0,b:256},white:{r:256,g:256,b:256}},findNear:function(c,a){if(c==0||c==255)return c;for(var f=256,j=0,g=0;g<a.length;g++){var d=Math.abs(c-a[g]);d<f&&(f=
d,j=a[g])}return j},get:function(c){c=c.replace("#","").toLowerCase();if(c=="000000"||c=="000"||c=="black")return"000000";if(c=="ffffff"||c=="fff"||c=="white")return"FFFFFF";if(this.namedColors[c])var a=this.namedColors[c],f=a.r,j=a.g,a=a.b;else if(/[^0-9a-f]/.test(c))return"000000";else c.length==3?(f=parseInt([c[0],c[0]].join(""),16),j=parseInt([c[1],c[1]].join(""),16),a=parseInt([c[2],c[2]].join(""),16)):c.length==6&&(f=parseInt(c.substring(0,2),16),j=parseInt(c.substring(2,4),16),a=parseInt(c.substring(4,
6),16));f=this.findNear(f,this.RG);j=this.findNear(j,this.RG);a=this.findNear(a,this.B);c=function(j){return j.length<=1?"0"+j:j};f=c(f.toString(16));j=c(j.toString(16));a=c(a.toString(16));return(f+j+a).toUpperCase()}},v={baseProps:["padding","border","margin"],partProps:["prev-char","prev-line","next-char","next-line"],setEdgeProps:function(c,a){var f=this;l.iter(this.baseProps,function(j){l.iteri(f.partProps,function(g,d){if(a[j][g]>0){var b=[j,d].join("-");c[b]=a[j][g]}})});return c},parseEdge:function(c){var a=
this,f={padding:[0,0,0,0],border:[0,0,0,0],margin:[0,0,0,0],sizeCharStep:0,sizeLineStep:0},j=function(b,e){b[0]=b[1]=b[2]=b[3]=e};l.iter(this.baseProps,function(b){c[b]&&j(f[b],parseInt(c[b]));l.iteri(a.partProps,function(e,d){var j=[b,d].join("-");c[j]&&(j=parseInt(c[j]),f[b][e]=j)})});for(var g=0;g<4;g++){var d=f.padding[g]+f.border[g]+f.margin[g];g%2==0?f.sizeCharStep+=d:f.sizeLineStep+=d}return f},parseBox:function(c){var a=this.parseEdge(c);a.width=parseInt(c.width||0);a.height=parseInt(c.height||
0);a.wrapWidth=a.width+a.sizeCharStep;a.wrapHeight=a.height+a.sizeLineStep;return a}},N=function(){function c(b){this.text=this._preprocess(b);this.pos=0;this.rb=""}var a=function(b,e){var d=b.indexOf(">",e+1);return d<0?"":b.substring(e,d+1)},f=function(b){b=b.split(/\s+/);b.shift();return l.map(b,function(b){return b.replace(/=.+/,"")})},j=function(b){var e={},b=b.match(k.rex.nvAttr);if(b==null)return e;l.iter(b,function(b){if(b.match(/([\w\-]+)=(.+)/)){var b=RegExp.$1.toLowerCase(),d=q.cutQuote(RegExp.$2);
e[b]=d}});return e},g=function(b){var b=b.replace(/[\s]+=[\s]+/g,"="),e=f(b),d=j(b);l.iter(e,function(b){typeof d[b]=="undefined"&&(d[b]=true)});return d},d=function(b){var e=b.replace("<","").replace("/>","").replace(">",""),b=e.split(/[\s\t\u3000]+/)[0].toLowerCase(),e=g(e);return{type:"tag",data:{name:b,attr:e}}},b=function(e,d,j){var a=e.indexOf("</"+d,j),j=e.indexOf("<"+d,j);return a<0?-1:j<0||a<j?a:b(e,d,a+1)},e=function(e,d,j){d=b(e,d,j);return e.substring(j,d)};c.prototype={getText:function(){return this.text},
_preprocess:function(b){for(var e="",d=0;d<k.layout.tabLength;d++)e+="&nbsp;";b=b.replace(/(\t)/,function(){return e}).replace(/<([\w\-]+)/g,function(b,e){return"<"+e.toLowerCase()}).replace(/<\/([\w\-]+)/g,function(b,e){return"</"+e.toLowerCase()}).replace(/\u201c([^\u201d]+)\u201d/g,"\u301d$1\u301f").replace(/<rp>[^<]*<\/rp>/gi,"").replace(/<rb><\/rb>/gi,"").replace(/<rt><\/rt>/gi,"").replace(/([^\n])<img/g,"$1\n<img").replace(/([^\n])<table/g,"$1\n<table").replace(/([^\n])<end-page/g,"$1\n<end-page").replace(/([^\n])<blockquote/g,
"$1\n<blockquote").replace(/([^\n])<indent/g,"$1\n<indent").replace(/([^\n])<iframe/g,"$1\n<iframe").replace(/([^\n])<ipage/g,"$1\n<ipage").replace(/([^\n])<ireader/g,"$1\n<ireader");k.system.conv_br?b=b.replace(/<br>/gi,"\n").replace(/<br \/>/gi,"\n"):k.system.nobr&&(b=b.replace(/<br>/gi,"").replace(/<br \/>/gi,""));return b},_peekChar:function(b){b=this.pos+(b||0);if(b==this.text.length)return"\n";if(b>this.text.length)throw"BufferEnd";return this.text.charAt(b)},_mapChar:function(b,e){var d=e.charCodeAt(0),
j={type:"char",data:e,vscale:1,hscale:1,half:r.isHankaku(e),pos:b},a=function(b,e,d){j.img=b;j.vscale=e||1;j.hscale=d||j.vscale;return j},g=function(b,e,d){j.cnv=b;j.vscale=e||1;j.hscale=d||j.vscale;return j};if(r.isSmallKana(e))return j.skana=true,j;if(e==" ")return g("&nbsp;");switch(d){case 12300:return a("kakko1",0.5);case 65378:return a("kakko1",0.5);case 12301:return a("kakko2",0.5);case 65379:return a("kakko2",0.5);case 12302:return a("kakko3",0.5);case 12303:return a("kakko4",0.5);case 65288:return a("kakko5",
0.5);case 40:return a("kakko5",0.5);case 65371:return a("kakko5",0.5);case 123:return a("kakko5",0.5);case 65289:return a("kakko6",0.5);case 41:return a("kakko6",0.5);case 65373:return a("kakko6",0.5);case 125:return a("kakko6",0.5);case 65308:return a("kakko7",0.5);case 60:return a("kakko7",0.5);case 12296:return a("kakko7",0.5);case 65310:return a("kakko8",0.5);case 62:return a("kakko8",0.5);case 12297:return a("kakko8",0.5);case 12298:return a("kakko9",0.5);case 8810:return a("kakko9",0.5);case 12299:return a("kakko10",
0.5);case 8811:return a("kakko10",0.5);case 65339:return a("kakko11",0.5);case 12308:return a("kakko11",0.5);case 91:return a("kakko11",0.5);case 65341:return a("kakko12",0.5);case 12309:return a("kakko12",0.5);case 93:return a("kakko12",0.5);case 12304:return a("kakko17",0.5);case 12305:return a("kakko18",0.5);case 65306:return a("tenten",0.5,1);case 58:return a("tenten",0.5,1);case 12290:return a("kuten",0.5);case 65377:return a("kuten",0.5);case 65294:return a("period",1);case 46:return a("period",
1);case 12289:return a("touten",0.5);case 65380:return a("touten",0.5);case 44:return a("touten",0.5);case 65292:return a("touten",0.5);case 65374:return a("kara",1);case 12316:return a("kara",1);case 8230:return a("mmm",1);case 8229:return a("mm",1);case 12317:return a("dmn1",1);case 12319:return a("dmn2",1);case 65309:return a("equal",1);case 61:return a("equal",1);case 12540:return a("onbiki",1);case 45:return g("\uff5c");case 8213:return g("\uff5c");case 65293:return g("\uff5c");case 9472:return g("\uff5c");
case 8593:return g("&#8594;");case 8594:return g("&#8595;");case 8658:return g("&#8595;");case 8595:return g("&#8592;");case 8592:return g("&#8593;")}return j},_mapTag:function(b,e){var d=e.data.name;return d=="ruby"?this._readRubyTag(b,e):d=="img"?this._readImgTag(b,e):m.isTcyTagName(d)?this._readTcyTag(b,e):m.isContentTagName(d)?this._readContentTag(b,e):e},_skipComment:function(b){this.pos=this.text.indexOf("--\>",b)+3},_readTag:function(b){var e=a(this.text,b),j=d(e);j.pos=b;this.pos+=e.length;
return j},_readContentTag:function(b,d){var a=e(this.text,d.data.name,this.pos);d.data.content=a;this.pos+=a.length+d.data.name.length+3;return d},_readTagGroup:function(b,j){var g=k.tags.group[j.data.name],c=e(this.text,j.data.name,this.pos);this.pos+=c.length+j.data.name.length+3;j.data.childs={};l.iter(g.childs,function(b){var g;g=c.indexOf("<"+b);if(g<0)g=null;else{var h=a(c,g);if(h=="")g=null;else{var C=d(h);C.data.content=e(c,b,g+h.length);g=C.data}}g!=null&&(j.data.childs[b]=g)});return j},
_readRubyTag:function(b,d){var a={type:"ruby",pos:b},j=e(this.text,d.data.name,this.pos);this.pos+=j.length+7;if(j.match(/<rt>([^<]+)<\/rt>/i))a.yomi=RegExp.$1;if(j.match(/<rb>([^<]+)<\/rb>/i))this.rb=a.kanji=RegExp.$1;else if(j.match(/([^<]+)<rt>/i))this.rb=a.kanji=RegExp.$1;return a},_readTcyTag:function(b,d){var a=e(this.text,d.data.name,this.pos);this.pos+=a.length+d.data.name.length+3;return{type:"tcy",data:a,pos:b}},_readImgTag:function(b,e){return e},_readRbChar:function(b){var e=this.rb.charAt(0);
this.rb=this.rb.substring(1);b=this._mapChar(b,e);b.type="rb";return b},_readSpecialChar:function(b,e){var d=this.text.substring(b).match(/&[a-zA-Z#0-9]+;/),d=d?d.toString():e;return d==""||d.length==1||d.length>10?(d=this._mapChar(b,e),this.pos++,d):(this.pos+=d.length,{type:"char",data:d,vscale:1,half:true,pos:b})},_readChar:function(b,e){var d=this._mapChar(b,e);this.pos++;return d},_readWord:function(b,e){var d=this.text.substring(b).match(k.rex.word),d=d?d.toString():e,a=L.isTcy(d)?"tcy":"word";
this.pos+=d.length;return d.length==1?this._mapChar(b,d):{type:a,data:d,pos:b}},getPos:function(){return this.pos},getToken:function(){var b=this.pos;if(this.rb!="")return this._readRbChar(b);else var e=this._peekChar();if(e=="<"){try{if(this._peekChar(1)=="!")return this._skipComment(b),this.getToken()}catch(d){}e=this._readTag(b);return this._mapTag(b,e)}else return e=="&"?this._readSpecialChar(b,e):e.match(k.rex.word)?this._readWord(b,e):this._readChar(b,e)}};return c}(),z=function(){function c(a){this.lexer=
new N(a);this.tokens=[];this.pos=0;this.eof=false;this.bufferSize=k.system.lexingBufferLen;this._doBuffer()}c.prototype={_doBuffer:function(){try{for(var a=0;a<this.bufferSize;a++)this.tokens.push(this.lexer.getToken())}catch(c){this.eof=true}},setPos:function(a){this.pos=a},getPos:function(){return this.pos},getText:function(){return this.lexer.getText()},isEnd:function(){return this.eof&&this.pos>=this.tokens.length-1},stepPos:function(a){this.pos+=typeof a!="undefined"?a:1},peekToken:function(a){return this.peekTokenByIndex(this.pos+
(a||0))},peekLastToken:function(){return this.peekTokenByIndex(this.tokens.length-1)},peekTokenByIndex:function(a){if(this.eof&&a>=this.tokens.length)throw"BufferEnd";a>=this.tokens.length&&this._doBuffer();var c=this.tokens[a];c.index=a;return c},findUntil:function(a,c,j){for(;;){if(a<0)break;else if(a>=this.tokens.length)break;else{var g=this.peekTokenByIndex(a);if(j(g))return g}a+=c}return null},getToken:function(){var a=this.peekToken();this.pos++;return a},getBufferRestSize:function(){return Math.max(this.tokens.length-
this.pos-1,0)},skipUntil:function(a){for(;;){var c=this.peekToken();if(!a(c))break;this.stepPos(1)}},skipUntilCRLF:function(){this.skipUntil(function(a){return!w.isTextToken(a)?false:a.data=="\r"||a.data=="\n"})},skipCRLF:function(){var a=this.peekToken();w.isTextToken(a)&&(a.data=="\r"?(this.stepPos(1),this.skipCRLF()):a.data=="\n"&&this.stepPos(1))}};return c}(),F=function(){function c(a){this.tags=[];this.tocs=[];this.topicPath=[];this.lastTopicPath=null;this.textSpaceNextChar=this.textSpacePrevChar=
this.seekTokenIndex=this.seekTextPos=this.seekCharCount=this.seekPageNo=this.seekNextLine=this.seekNextChar=0;this.lineChars=[];this.rubyList=[];this.inlinePages=[];this.curToc=null;this.greedyMode=false;this.labelAttr=null;this.fontColor=k.color.defCharImgColor;this.updateFontSize(a.fontSize)}c.prototype={getSnap:function(){var a={},c=q.clone,j="tags,tocs,topicPath,lastTopicPath,seekNextChar,seekNextLine,seekCharCount,seekTextPos,seekTokenIndex,textSpaceBefore,textSpaceNextChar,lineChars,rubyList,inlinePages,curToc,greedyMode,labelAttr,fontSize,fontSize2,fontSize4,fontColor".split(",");
for(prop in j)a[prop]=c(this[prop]);return a},restoreSnap:function(a){for(prop in a)this[prop]=a[prop]},createBlock:function(a,c){return s.init({},{type:"block",id:void 0,name:"",width:0,height:0,wrapWidth:0,wrapHeight:0,content:""},c)},createImg:function(a,c){return s.init(this.createBlock(a,c),{src:""},c)},createInlineFrame:function(a,c){return s.init(this.createBlock(a,c),{src:"",frameborder:0},c)},createCaption:function(a,c){return s.init({},{type:"caption",data:"",captionPos:"",fontSize:a.captFontSize,
height:a.captFontSize+a.captMargin,"text-align":"center","margin-top":0,"margin-bottom":0},c)},createRuby:function(a,c){return s.init({},{type:"ruby",data:"",fontSize:this.fontSize2,textFontSize:this.fontSize,direction:a.direction,position:{x:0,y:0}},c)},createLine:function(a){if(this.labelAttr!=null){var c=this.createLabelLine(a,this.labelAttr);this.textSpacePrevChar=Math.max(0,this.textSpacePrevChar-a.labelSpace*2);this.textSpaceNextChar=Math.max(0,this.textSpaceNextChar-a.labelSpace*2);this.labelAttr=
null}else c=this.createTextLine(a),this.fixRubyPos(a);this.lineChars=[];this.rubyList=[];this.seekNextChar=0;return c},createTextLine:function(a){var c=this.getMaxFontSizeOfLine(a),j=a.enableRuby?Math.floor(c*a.leadingRate):c,g=this.getTextSpaceSize(),d=a.isVertical?j:a.maxNextChar-g,j=a.isVertical?a.maxNextChar-g:j,c={width:a.isVertical?c:a.width,height:a.isVertical?a.height:c};return{type:"line",width:d,height:j,direction:a.direction,fontSize:a.fontSize,textLineSize:c,rubyLineSize:{width:a.enableRuby?
a.isVertical?d-c.width:a.width:0,height:a.enableRuby?a.isVertical?a.height:j-c.height:0},childs:this.lineChars,rubyList:this.rubyList}},createLabelLine:function(a,c){var j=this.getMaxFontSizeOfLine(a),g=Math.floor(j*a.leadingRate),j=a.isVertical?g:this.seekNextChar+2*a.labelSpace,g=a.isVertical?this.seekNextChar+2*a.labelSpace:g;return{type:"label-line",width:j,height:g,direction:a.direction,fontSize:a.fontSize,textLineSize:{width:j,height:g},rubyLineSize:{width:0,height:0},childs:this.lineChars,
textSpacePrevChar:a.labelSpace,textSpaceNextChar:a.labelSpace,rubyList:[],attr:c}},createPage:function(a,c,j,g){return{type:"page",direction:a,width:c,height:j,childs:g}},createErrorMsg:function(a,c){var j=a.fontSize*5;return this.createInlineReader(a,{direction:"horizontal",width:a.isVertical?j:a.maxNextChar,height:a.isVertical?a.maxNextChar:j,theme:"error","class":"error",nopager:true,content:c})},createInlineReader:function(a,c){return s.init({},{type:"ireader","class":"",direction:a.direction,
width:0,height:0,wrapWidth:0,wrapHeight:0,border:k.layout.readerBorder,fontSize:a.fontSize,theme:"",syntax:"",nopager:false,content:""},c)},getTocs:function(){return this.tocs},pushTextToken:function(a){a.type=="char"||a.type=="rb"||a.type=="tcy"?this.pushCharToken(a):a.type=="word"&&this.pushWordToken(a)},pushTagToken:function(a){this.lineChars.push(a)},pushCharToken:function(a){this.seekNextChar+=a.advanceSize;this.lineChars.push(a);w.isCharCountableToken(a)&&this.seekCharCount++;this.curToc!=null&&
(this.curToc.title+=a.data)},pushWordToken:function(a){this.seekNextChar+=a.advanceSize;this.lineChars.push(a);this.seekCharCount+=a.data.length;this.curToc!=null&&(this.curToc.title+=a.data)},pushTopicPath:function(a){this.lastTopicPath!=null&&(a.level<this.lastTopicPath.level?(this.topicPath.pop(),this.topicPath.pop()):a.level==this.lastTopicPath.level&&this.topicPath.pop());this.topicPath.push(a);this.lastTopicPath=a},pushTocStartToken:function(a){var c=a.data.attr;this.curToc={level:c.level,title:"",
pageNo:this.seekPageNo,id:c.id};this.tocs.push(this.curToc);this.pushTagToken(a)},pushTocEndToken:function(a){this.pushTopicPath(this.curToc);this.curToc=null;this.pushTagToken(a)},pushRubyToken:function(a,c){this.rubyList.push(this.createRuby(a,{fontSize:Math.floor(this.fontSize*k.layout.rubySizeRate),textFontSize:this.fontSize,data:c.yomi,position:a.isVertical?{x:0,y:this.seekNextChar}:{x:this.seekNextChar,y:Math.floor((a.lineSpaceRate-k.layout.rubySizeRate)*this.fontSize/2)}}))},fixRubyPos:function(a){var c=
this.getMaxFontSizeOfLine(a);c!=a.fontSize&&l.iter(this.rubyList,function(j){if(j.textFontSize<c)a.isVertical?j.position.x=-Math.floor((c-j.textFontSize)/2):j.position.y=Math.floor((c-j.textFontSize)*(1+a.lineSpaceRate))})},startLabel:function(a,c){this.textSpacePrevChar+=a.labelSpace*2;this.textSpaceNextChar+=a.labelSpace*2;this.labelAttr=c.data.attr},endLabel:function(){},getTextSpaceSize:function(){return this.textSpacePrevChar+this.textSpaceNextChar},getRestCharSpace:function(a){return a.maxNextChar-
this.seekNextChar-this.getTextSpaceSize()},getRestLineSpace:function(a){return a.maxNextLine-this.seekNextLine},getRestWidth:function(a){return a.isVertical?this.getRestLineSpace(a):this.getRestCharSpace(a)},getRestHeight:function(a){return a.isVertical?this.getRestCharSpace(a):this.getRestLineSpace(a)},getMaxFontSizeOfLine:function(){return l.fold(this.lineChars,k.layout.minFontSize,function(a,c){return typeof c.fontSize!="undefined"&&c.fontSize>a?c.fontSize:a})},getCurFontSize:function(a){for(i=
this.tags.length-1;i>=0;i--){var c=this.tags[i];if(c.name=="font"&&typeof c.attr.scale!="undefined")return Math.floor(a*c.attr.scale)}return a},getCurFontColor:function(){for(i=this.tags.length-1;i>=0;i--){var a=this.tags[i];if(a.name=="font"&&typeof a.attr.color!="undefined")return a.attr.color}return k.color.defCharImgColor},updateFontSize:function(a){this.fontSize=a;this.fontSize2=Math.floor(a/2);this.fontSize4=Math.floor(a/4)},updateFontColor:function(a){this.fontColor=M.get(a)},pushTag:function(a){this.tags.push(a)},
popTag:function(a){for(var c=[];this.tags.length>0;){var j=this.tags.pop();if(j.name==a)break;c.push(j)}for(;c.length>0;)this.tags.push(c.pop())}};return c}(),I={code:{fontSizeRate:0.7,leadingRate:1.8},error:{fontSizeRate:1,leadingRate:1.8}},y=function(){function c(a){s.init(this,{direction:"vertical",theme:null,leadingRate:k.layout.defLeadingRate,width:400,height:300,fontSize:16,enableRuby:true,disableTailSpace:false,charImgColor:"000000"},a);this.update()}var a={"vertical-rl":{"page-size":"width",
"block-float":"right","line-text-align":"center","ruby-line-text-align":"left","padding-prev-char":"padding-top","padding-next-char":"padding-bottom","padding-prev-line":"padding-right","padding-next-line":"padding-left","border-prev-char":"border-top","border-next-char":"border-bottom","border-prev-line":"border-right","border-next-line":"border-left","margin-prev-char":"margin-top","margin-next-char":"margin-bottom","margin-prev-line":"margin-right","margin-next-line":"margin-left"},"horizontal-lr":{"page-size":"height",
"block-float":"left","line-text-align":"left","ruby-line-text-align":"left","padding-prev-char":"padding-left","padding-next-char":"padding-right","padding-prev-line":"padding-top","padding-next-line":"padding-bottom","border-prev-char":"border-left","border-next-char":"border-right","border-prev-line":"border-top","border-next-line":"border-bottom","margin-prev-char":"margin-left","margin-next-char":"margin-right","margin-prev-line":"margin-top","margin-next-line":"margin-bottom"}};c.prototype={update:function(){if(this.theme!=
null)this.fontSize=Math.floor(this.fontSize*(this.theme.fontSizeRate||1)),this.leadingRate=this.theme.leadingRate||this.leadingRate;this.directionX=(this.isVertical=this.direction.match(/vertical/)?true:false)?"rl":"lr";this.directionY="tb";var c=[this.direction,this.directionX].join("-");this.cssPropMap=a[c];this.lineSpaceRate=this.leadingRate-1;this.blockMargin=Math.floor(this.fontSize*k.layout.blockMarginRate);this.labelSpace=Math.floor(this.fontSize*this.lineSpaceRate/2);this.captFontSize=Math.floor(this.fontSize*
k.layout.captionSizeRate);this.captMargin=Math.floor(this.captFontSize*k.layout.captionMarginRate);this.isVertical?(this.spaceForHeadNG=this.disableTailSpace?0:Math.floor(this.fontSize/2),this.maxNextChar=this.height-this.spaceForHeadNG,this.maxNextLine=this.width):(this.spaceForHeadNG=this.disableTailSpace?0:this.fontSize,this.maxNextChar=this.width-this.spaceForHeadNG,this.maxNextLine=this.height)},getCssProp:function(a){return this.cssPropMap[a]},getBlockRestWidth:function(a){return this.isVertical?
a:this.width-a},getBlockRestHeight:function(a){return this.isVertical?this.height-a:a}};return c}(),J=function(){function c(a){this.forks=[];this.rest_size_list=a}function a(a,g,d){this.lexer=a;this.layout=g;this.ctx=typeof d!="undefined"?d:new F(g);this.forkset=null;this.pushBlocks=[];this.finish=false;this.onParseElementBefore=function(b,e,d,a){return a}}var f=function(a,g){switch(g.type){case "block":case "ireader":return a.isVertical?g.wrapWidth:g.wrapHeight;case "page":return a.isVertical?g.wrapWidth||
g.width:g.wrapHeight||g.height;default:return a.isVertical?g.width:g.height}};c.prototype={add:function(a){this.forks.push(a)},hasNext:function(){return l.exists(this.forks,function(a){return a.hasNext()})},mergePages:function(a,g,d){if(d.length==1)return d[0];var b=l.fold(d,0,function(b,e){var d=f(a,e);return d>b?d:b}),e=a.isVertical?"width":"height";l.iter(d,function(d){d[e]=d.size=b});return g.createPage(a.direction,a.isVertical?b:a.width,a.isVertical?a.height:b,d)},yieldPage:function(a,g){var d=
a.isVertical?"width":"height",b=this.rest_size_list.length>0?this.rest_size_list.shift():a[d],e=l.map(this.forks,function(e){var a=e.layout[d];e.layout[d]=b-(e.edge?e.edge.sizeLineStep:0);a!=e.layout[d]&&e.layout.update();e=e.parsePage();e.forked=true;return e});return this.mergePages(a,g,e)}};a.prototype={getContext:function(){return this.ctx},getPercent:function(a){return 100*a.spos/this.lexer.lexer.text.length},hasNext:function(){return!this.finish},hasForkNext:function(){return l.exists(this.forks,
function(a){return a.hasNext()})},findTextToken:function(a,g,d,b){for(var e=null,c={token:null,tags:[]},B=b;B<b+50;B++){var f=a.peekTokenByIndex(B);if(w.isBlockToken(f))break;if(w.isTextToken(f)){this.parseMetrics(a,g,e==null?d:e,f);c.token=f;break}if(f.type=="tag"){c.tags.push(f);var o=f.data.name;if(o=="font")e=e==null?q.clone(d):e,e.pushTag(f.data),e.fontSize=e.getCurFontSize(g.fontSize);else if(o=="/font")e=e==null?q.clone(d):e,e.popTag("font"),e.fontSize=e.getCurFontSize(g.fontSize)}}return c},
pushTextToLine:function(a,g,d,b){var e=d.getRestCharSpace(g),c=this.findTextToken(a,g,d,b.index+1);if(!(d.seekNextChar==0&&b.data==" "&&c.token.type=="word"))if(c.token==null||c.token.data=="\r"||c.token.data=="\n")d.pushTextToken(b);else if(e-b.advanceSize>=c.token.advanceSize||c.token.advanceSize>=g.maxNextChar)d.pushTextToken(b);else{if(k.system.lineBreakCheckLevel==0)throw"LineEnd";if(r.isTailNg(b.data))throw a.setPos(b.index),"LineEnd";if(!r.isHeadNg(c.token.data)||c.token.type=="word")throw d.pushTextToken(b),
a.skipCRLF(),"LineEnd";if(k.system.lineBreakCheckLevel==1)throw"LineEnd";e=this.findTextToken(a,g,d,c.token.index+1);if(e.token==null||!r.isHeadNg(e.token.data)){e.token.fontSize=g.fontSize;d.pushTextToken(b);d.pushTextToken(c.token);a.setPos(c.token.index+1);a.skipCRLF();for(b=0;b<c.tags.length;b++)this.parseLineTag(a,g,d,c.tags[b]);throw"LineEnd";}a.setPos(b.index);throw"LineEnd";}},pushLongWordToLine:function(a,g,d,b){var e=d.getRestCharSpace(g),c=Math.floor(e/d.fontSize2),f=b.data.length,e=b.data.substring(0,
c),c=b.data.substring(c,f),f=q.clone(b);f.data=e;this.parseMetrics(a,g,d,f);d.pushTextToken(f);a.setPos(b.index);b.data=c;this.parseMetrics(a,g,d,b);throw"LineEnd";},parseMetrics:function(a,c,d,b){b.type=="char"||b.type=="rb"?b.src?this.parseMetricsIconChar(a,c,d,b):b.img?this.parseMetricsImgChar(a,c,d,b):this.parseMetricsChar(a,c,d,b):b.type=="tcy"?this.parseMetricsTcy(a,c,d,b):b.type=="word"&&this.parseMetricsWord(a,c,d,b)},parseMetricsChar:function(a,c,d,b){a=c.isVertical?b.vscale:b.hscale;b.fontSize=
d.fontSize;b.advanceSize=a!=1?Math.floor(d.fontSize*a):d.fontSize;if(c.isVertical){if(b.cnv&&b.cnv=="&nbsp;")b.advanceSize=d.fontSize2}else if(b.half)b.advanceSize=d.fontSize2},parseMetricsImgChar:function(a,c,d,b){this.parseMetricsChar(a,c,d,b);if(c.isVertical)b.color=d.fontColor;if(k.system.enableYakuMetricsCheck)if(b.img=="tenten")b.advanceSize+=b.advanceSize;else if(!(b.img.indexOf("kakko")<0&&b.img!="touten"&&b.img!="kuten")){var e=function(b){return w.isTextToken(b)||b.type=="ruby"},h=a.findUntil(b.index-
1,-1,e),f="";if(h!=null)w.isTextToken(h)?f=h.data:h.type=="ruby"&&(f=h.kanji.substring(-1));e=a.findUntil(b.index+1,1,e);h="";if(e!=null)w.isTextToken(e)?h=e.data:e.type=="ruby"&&(h=e.kanji.substring(0,1));c.isVertical?this.parseMetricsMarginVert(a,c,d,b,f,h):this.parseMetricsMarginHori(a,c,d,b,f,h)}},parseMetricsMarginVert:function(a,c,d,b,e,h){if(r.isKakkoStartChar(b.data)&&e!=""){if(!r.isKakkoStartChar(e)&&!r.isKutenTouten(e))b["margin-prev-char"]=d.fontSize2,b.advanceSize=d.fontSize}else if(r.isKakkoEndChar(b.data)&&
h!=""){if(!r.isKakkoEndChar(h)&&!r.isKutenTouten(h))b["margin-next-char"]=d.fontSize2,b.advanceSize=d.fontSize}else if(r.isKutenTouten(b.data)&&!r.isKakkoEndChar(h)&&!r.isKutenTouten(h))b["margin-next-char"]=d.fontSize2,b.advanceSize=d.fontSize},parseMetricsMarginHori:function(a,c,d,b,e,h){if(t.isIE||b.fontSize<=k.layout.minKerningFontSize)b.hscale=1;else if(r.isKakkoStartChar(b.data)&&h!=""){if(!r.isKakkoStartChar(h))b.hscale=1}else if(r.isKakkoEndChar(b.data)&&h!=""){if(!r.isKakkoEndChar(h)&&!r.isKutenTouten(h))b.hscale=
1}else if(r.isKutenTouten(b.data)&&h!=""&&!r.isKakkoEndChar(h)&&!r.isKutenTouten(h))b.hscale=1},parseMetricsIconChar:function(a,c,d,b){a=c.isVertical?b.height:b.width;b.fontSize=a;b.advanceSize=a},parseMetricsTcy:function(a,c,d,b){b.fontSize=d.fontSize;b.advanceSize=d.fontSize},parseMetricsWord:function(a,c,d,b){b.fontSize=d.fontSize;b.advanceSize=b.data.length*d.fontSize2},parseChar:function(a,c,d,b){if(b.data!="\r"){if(b.data=="\n")throw"LineEnd";b.data==" "&&!d.greedyMode&&a.skipUntil(function(b){return b.type==
"char"&&b.data==" "});this.parseMetrics(a,c,d,b);this.pushTextToLine(a,c,d,b)}},parseWord:function(a,c,d,b){typeof b.advanceSize=="undefined"&&this.parseMetrics(a,c,d,b);b.advanceSize>c.maxNextChar?this.pushLongWordToLine(a,c,d,b):this.pushTextToLine(a,c,d,b)},parseRuby:function(a,c,d,b){d.pushRubyToken(c,b)},parseFontStart:function(a,c,d,b){a=b.data.attr;if(typeof a.scale!="undefined")c=a.scale=parseFloat(a.scale),d.updateFontSize(Math.floor(d.fontSize*c));typeof a.color!="undefined"&&d.updateFontColor(a.color);
d.pushTag(b.data);d.pushTagToken(b)},parseFontEnd:function(a,c,d,b){d.pushTagToken(b);d.popTag("font");a=d.getCurFontSize(c.fontSize);c=d.getCurFontColor();d.updateFontSize(a);d.updateFontColor(c)},parseHeaderStart:function(a,c,d,b){var e=parseInt(b.data.name.substring(1))-1,e=k.layout.header[e];b.data.name="font";b.data.attr.scale=e.scale;b.data.attr["class"]=k.className.header;this.parseFontStart(a,c,d,b)},parseHeaderEnd:function(a,c,d,b){b.data.name="/font";this.parseFontEnd(a,c,d,b);a.skipCRLF();
throw"LineEnd";},parseTocStart:function(a,c,d,b){a=b.data.attr;a.level=parseInt(a.level||0);a.id=a.id||"";d.pushTocStartToken(b)},parseTocEnd:function(a,c,d,b){d.pushTocEndToken(b)},parseLabelStart:function(a,c,d,b){a.skipCRLF();d.updateFontColor(k.color.labelCharImgColor);d.startLabel(c,b)},parseLabelEnd:function(a,c,d,b){a=d.getCurFontColor();d.updateFontColor(a);d.endLabel(c,b);throw"LineEnd";},parseIcon:function(a,c,d,b){var e=b.data.attr;b.width=parseInt(e.width||d.fontSize);b.height=parseInt(e.height||
d.fontSize);b["class"]=e["class"]||"";b.src=e.src;b.type="char";delete b.data;b.data="";this.parseMetrics(a,c,d,b);this.pushTextToLine(a,c,d,b)},parseLineTag:function(a,c,d,b){switch(b.data.name){case "br":throw"LineEnd";case "pre":d.greedyMode=true;break;case "/pre":d.greedyMode=false;break;case "font":this.parseFontStart(a,c,d,b);break;case "/font":this.parseFontEnd(a,c,d,b);break;case "h1":case "h2":case "h3":case "h4":case "h5":case "h6":this.parseHeaderStart(a,c,d,b);break;case "/h1":case "/h2":case "/h3":case "/h4":case "/h5":case "/h6":this.parseHeaderEnd(a,
c,d,b);break;case "toc":this.parseTocStart(a,c,d,b);break;case "/toc":this.parseTocEnd(a,c,d,b);break;case "part":case "chapter":case "section":case "subsection":b.data.attr.level=S.getLevel(b.data.name);b.data.name="toc";this.parseTocStart(a,c,d,b);break;case "/part":case "/chapter":case "/section":case "/subsection":b.data.name="/toc";this.parseTocEnd(a,c,d,b);break;case "label":this.parseLabelStart(a,c,d,b);break;case "/label":this.parseLabelEnd(a,c,d,b);break;case "icon":this.parseIcon(a,c,d,
b);break;default:d.pushTagToken(b)}},parseLine:function(a,c,d){try{for(;;){var b=a.getToken();switch(b.type){case "char":case "rb":case "tcy":this.parseChar(a,c,d,b);break;case "word":this.parseWord(a,c,d,b);break;case "ruby":this.parseRuby(a,c,d,b);break;case "tag":this.parseLineTag(a,c,d,b)}}}catch(e){return e!="LineEnd"&&H(e),d.createLine(c)}},parseBlockCaptions:function(a,c,d,b){var e=[];l.iter(["caption-head","caption-foot"],function(d){b[d]&&e.push(c.createCaption(a,{data:b[d],captionPos:d,
"margin-bottom":d=="caption-head"?a.captMargin:0,"margin-top":d=="caption-foot"?a.captMargin:0}))});return e},parseBlockSize:function(a,c,d,b){var e=c.getRestWidth(a),c=c.getRestHeight(a),b=l.fold(b,0,function(a,b){return a+b.height});if(d.width<=0||d.height<=0)return d.error="block size invalid("+d.width+","+d.height+")",d;var h=d.wrapWidth-d.width,f=d.wrapHeight-d.height,n=d.wrapWidth,o=d.wrapHeight+b;if(n<e&&o<c)return d;if(n<a.maxBlockWidth&&o<a.maxBlockHeight)throw"Overflow";n>e&&(a=e*o/n,n=
Math.max(1,Math.floor(e)),o=Math.max(1,Math.floor(a)));o>c&&(n=Math.floor(n*c/o),o=Math.floor(c));d.wrapWidth=n;d.wrapHeight=Math.max(0,o-b);d.width=Math.max(0,d.wrapWidth-h);d.height=Math.max(0,d.wrapHeight-f);return d},parseImg:function(a,c,d,b){var b=b.data.attr,e=v.parseBox(b),e=v.setEdgeProps(d.createImg(c,{name:"img",id:b.id,width:e.width,height:e.height,wrapWidth:e.wrapWidth,wrapHeight:e.wrapHeight,border:e.border,src:b.src}),e);return this.parseBlockElement(a,c,d,e,b)},parseTable:function(a,
c,d,b){var e=b.data.attr,h=v.parseBox(e),b=v.setEdgeProps(d.createBlock(c,{id:e.id,width:h.width,height:h.height,wrapWidth:h.wrapWidth,wrapHeight:h.wrapHeight,content:b.data.content,name:b.data.name}),h);return this.parseBlockElement(a,c,d,b,e)},parseTextarea:function(a,c,d,b){var e=b.data.attr,h=v.parseBox(e),b=v.setEdgeProps(d.createBlock(c,{id:e.id,width:h.width,height:h.height,wrapWidth:h.wrapWidth,wrapHeight:h.wrapHeight,content:b.data.content,name:b.data.name}),h),b=this.parseBlockElement(a,
c,d,b,e);return s.copy(b,{onclick:e.onclick||""})},parseInlineFrame:function(a,c,d,b){var e=b.data.attr,h=v.parseBox(e),b=v.setEdgeProps(d.createInlineFrame(c,{id:e.id,width:h.width,height:h.height,wrapWidth:h.wrapWidth,wrapHeight:h.wrapHeight,content:b.data.content,name:b.data.name,src:e.src||"",frameborder:parseInt(e.frameborder||0)}),h);return this.parseBlockElement(a,c,d,b,e)},parseInlineBox:function(a,c,d,b){var e=b.data.attr,h=v.parseBox(e),b=v.setEdgeProps(d.createBlock(c,{id:e.id,width:h.width,
height:h.height,wrapWidth:h.wrapWidth,wrapHeight:h.wrapHeight,content:b.data.content,name:b.data.name}),h);return this.parseBlockElement(a,c,d,b,e)},parseInlinePage:function(a,c,d,b){b.data.attr.nopager=true;return this.parseInlineReader(a,c,d,b)},parseInlineReader:function(a,c,d,b){var e=b.data.attr;e.border=parseInt(e.border||k.layout.readerBorder);var h=v.parseBox(e),b=v.setEdgeProps(d.createInlineReader(c,{id:e.id,"class":e["class"]||"",direction:e.direction||c.direction,width:h.width,height:h.height,
wrapWidth:h.wrapWidth,wrapHeight:h.wrapHeight,fontSize:parseInt(e["font-size"]||c.fontSize),theme:e.theme||"",syntax:e.syntax||"",nopager:e.nopager||false,content:q.cutHeadCRLF(b.data.content)}),h);return this.parseBlockElement(a,c,d,b,e)},parseBlockElement:function(a,c,d,b,e){s.init(b,{"class":e["class"]||"",align:"",direction:c.direction},e);var h=this.parseBlockCaptions(c,d,b,e),b=this.parseBlockSize(c,d,b,h);if(b.error)return d.createErrorMsg(c,"&lt;"+b.name+"&gt; "+b.error);h.length>0&&(b=this.parseBlockWithCaption(a,
c,d,b,h));if(e.pushed)return this.parseBlockWithPush(a,c,d,b);else b.align!=""&&(b=this.parseBlockWithAlign(a,c,d,b));return b},parseBlockWithCaption:function(a,c,d,b,e){var h=[b],a=b.wrapWidth,f=b.wrapHeight;l.iter(e,function(a){f+=a.height;a.captionPos=="caption-head"?h.unshift(a):h.push(a)});d=d.createPage(b.direction,a,f,h);s.copy(d,{"class":b["class"]||"",direction:b.direction,align:b.align,width:a,height:f,wrapWidth:a,wrapHeight:f});delete b.align;delete b["class"];return d},parseBlockWithPush:function(a,
c,d,b){var e=c.blockMargin,h=(c.isVertical?b.wrapWidth:b.wrap_heigh)+e;if(d.seekNextLine+h<c.maxNextLine)d.seekNextLine+=h,b.push_size=h,b["margin-prev-line"]=e,this.pushBlocks.push(b);return this.parseElement(a,c,d)},parseBlockWithAlign:function(c,g,d,b){var e=b.align=="top"||b.align=="left",h=b.direction?b.direction==g.direction:true,f={};f[e?"margin-prev-char":"margin-next-char"]=g.blockMargin;aligned_edge=v.parseEdge(f);var n=g.getBlockRestWidth(b.wrapWidth)-(g.isVertical?aligned_edge.sizeLineStep:
aligned_edge.sizeCharStep),o=g.getBlockRestHeight(b.wrapHeight)-(g.isVertical?aligned_edge.sizeCharStep:aligned_edge.sizeLineStep),f=d.seekNextLine;d.seekNextLine=0;c=new a(c,new y({width:n,height:o,fontSize:g.fontSize,direction:g.direction,disableTailSpace:h}),d);c.edge=aligned_edge;c.aligned=true;c.parent=this;c.offset=f;h=c.parsePage();d.seekNextLine=f;h.aligned=true;this.forkset=c.forkset;return d.createPage(g.direction,g.isVertical?b.wrapWidth:g.width,g.isVertical?g.height:b.wrapHeight,e?[b,
h]:[h,b])},parseBlockTag:function(a,c,d,b){a.stepPos();a.skipCRLF();switch(b.data.name){case "img":return this.parseImg(a,c,d,b);case "table":return this.parseTable(a,c,d,b);case "textarea":return this.parseTextarea(a,c,d,b);case "iframe":return this.parseInlineFrame(a,c,d,b);case "ibox":return this.parseInlineBox(a,c,d,b);case "ipage":return this.parseInlinePage(a,c,d,b);case "ireader":return this.parseInlineReader(a,c,d,b)}return null},parseIndent:function(a,c,d,b){var e=b.data.attr,h=k.layout.indent;
e.before=parseInt(e.before||h.indentBefore);e.after=parseInt(e.after||h.indentAfter);if(e.count)e.before=e.after=parseInt(e.count);e.border=parseInt(e.border||0);e["margin-prev-char"]=c.fontSize*e.before;e["margin-next-char"]=c.fontSize*e.after;return this.parseSingleForkPage(a,c,d,b)},parseBlockquote:function(a,c,d,b){var e=b.data.attr,h=k.layout.blockquote;e["font-size"]=parseInt(e["font-size"]||Math.floor(c.fontSize*h.fontSizeRate));e.border=parseInt(e.border||h.border);b.data.content=m.wrap("indent",
{before:h.indentBefore,after:h.indentAfter,theme:e.theme||"",syntax:e.syntax||""},b.data.content);e.theme="";e.syntax="";return this.parseSingleForkPage(a,c,d,b)},parseFieldset:function(a,c,d,b){var e=b.data.attr,h=k.layout.fieldset,f=q.cutTagHeadSpace(b.data.content).replace(/<\/legend>[\s]+/,"</legend>").replace(/<legend([^>]*)>(.+)<\/legend>/,"\n<label$1>$2</label>\n");e.border=h.border||1;e["font-size"]=parseInt(e["font-size"]||Math.floor(c.fontSize*h.fontSizeRate));b.data.content=m.wrap("indent",
{before:h.indentBefore,after:h.indentAfter,raw:true,theme:e.theme||"",syntax:e.syntax||""},f);e.theme="";e.syntax="";return this.parseSingleForkPage(a,c,d,b)},parseDL:function(a,c,d,b){var e=b.data.attr,h=k.layout.dl;b.data.content=q.cutTagHeadSpace(b.data.content);if(h.indentBefore>0||h.indentAfter>0)e.border=0,b.data.content=m.wrap("indent",{before:h.indentBefore,after:h.indentAfter},b.data.content);return this.parseSingleForkPage(a,c,d,b)},parseDT:function(a,c,d,b){var e=k.layout.dl.dt,h=b.data.attr;
h["font-size"]=parseInt(h["font-size"]||Math.floor(c.fontSize*e.fontSizeRate));b.data.content=q.cutTagHeadSpace(b.data.content);b.data.content=m.wrap("strong",{},b.data.content);return this.parseSingleForkPage(a,c,d,b)},parseDD:function(a,c,d,b){var e=k.layout.dl.dd,h=b.data.attr;h["font-size"]=parseInt(h["font-size"]||Math.floor(c.fontSize*e.fontSizeRate));b.data.content=q.cutTagHeadSpace(b.data.content);b.data.content=m.wrap("indent",{before:e.indentBefore,after:e.indentAfter},b.data.content);return this.parseSingleForkPage(a,
c,d,b)},parseSingleForkPage:function(j,g,d,b){var e=b.data.content,b=b.data.attr,j=v.parseEdge(b),h=d.getRestLineSpace(g),f=parseInt(b["font-size"]||g.fontSize),n=g.isVertical?h-j.sizeLineStep:g.maxNextChar-j.sizeCharStep,o=g.isVertical?g.maxNextChar-j.sizeCharStep:h-j.sizeLineStep,k=b.theme?I[b.theme]:null,e=new z(e),f=new y({direction:g.direction,width:n,height:o,theme:k,fontSize:f}),e=new a(e,f);e.args=b;e.edge=j;e.forked=true;e.parent=this;b=[h];this.aligned&&b.push(this.parent.layout.maxNextLine-
(g.maxNextLine+this.offset));this.forkset=new c(b);this.forkset.add(e);return this.forkset.yieldPage(g,d)},parseTextset:function(a,c,d,b){var e=b,h=k.layout.textset;for(e.childs=[];;)if(b=a.getToken(),b.type=="tag"){var f=b.data.name,n=b.data.attr;if(f=="/textset")break;if(f=="tpart")n.scale=parseFloat(n.scale||h.tpart.fontSizeRate),e.childs.push(b.data)}return this.parseSetForkPage(a,c,d,e)},parseUL:function(a,c,d,b){var e=b.data.attr,h=k.layout.ul,f=b.data.content.replace(/[\s]+(<\/?li)/gi,"$1");
e.border=0;b.data.content=m.wrap("indent",{before:h.indentBefore,after:h.indentAfter},f);this.liCount=1;return this.parseSingleForkPage(a,c,d,b)},parseLI:function(a,c,d,b){var e={childs:[]},h=this.parent.parent.forktag,f=k.layout[h]||k.layout.ul,n=f.li,b=b.data,n=parseFloat(b.attr.scale||n.fontSizeRate),o=Math.floor(c.fontSize*n);this.liIndex=this.parent.parent.liCount++;h=="ol"?c.isVertical?(f=o+o,h="<pack>"+this.liIndex+"</pack>&nbsp;"):(f=Math.floor(o*2.5),h=this.liIndex+".&nbsp;"):(h=f.listMark,
f=o);h={content:h,attr:{scale:n,size:f}};b.attr.scale=n;b.content=q.cutEdgeCRLF(b.content);e.childs.push(h);e.childs.push(b);return this.parseSetForkPage(a,c,d,e)},parseScenario:function(a,c,d,b){var e=b,h={},f=k.layout.scenario;for(e.childs=[];;)if(b=a.getToken(),b.type=="tag"){var b=b.data,n=b.name,o=b.attr;if(n=="/scenario")break;switch(n){case "sbody":var E=Math.floor(c.fontSize*f.sbody.marginRate);o.scale=parseFloat(o.scale||f[n].fontSizeRate);b.args={};b.args["margin-prev-char"]=E;b.args["margin-next-char"]=
E;h[n]=b;break;case "shead":case "sfoot":o.scale=parseFloat(o.scale||f[n].fontSizeRate),o.size=parseInt(o.size||f[n].size),h[n]=b}}f=["shead","sbody","sfoot"];for(b=0;b<f.length;b++)n=f[b],h[n]&&e.childs.push(h[n]);return this.parseSetForkPage(a,c,d,e)},parseSetForkPage:function(j,g,d,b){var e=this,j=b.childs,b=l.filter(j,function(a){return typeof a.attr.size!="undefined"}),h=l.fold(b,0,function(a,b){return a+parseInt(b.attr.size)}),f=Math.floor(((g.isVertical?g.height:g.width)-h)/(j.length-b.length)),
n=d.getRestLineSpace(g),k=function(b,c,d,C){b=new a(new z(b),new y({direction:g.direction,width:g.isVertical?n:c,height:g.isVertical?c:n,fontSize:d}));b.args=C;b.parent=e;return b},b=[n];this.aligned&&b.push(this.parent.layout.maxNextLine-(g.maxNextLine+this.offset));this.forkset=new c(b);b=0;for(h=j.length;b<h;b++)(function(a){var b=parseInt(a.attr.size||f);a.args=a.args||{};b-=a.args["margin-prev-char"]||0;b-=a.args["margin-next-char"]||0;var c=Math.floor(parseFloat(a.attr.scale||1)*g.fontSize);
e.forkset.add(k(a.content,b,c,a.args))})(j[b]);return this.forkset.yieldPage(g,d)},parseForkPageTag:function(a,c,d,b){a.stepPos();a.skipCRLF();switch(b.data.name){case "indent":return this.parseIndent(a,c,d,b);case "blockquote":return this.parseBlockquote(a,c,d,b);case "ul":return this.parseUL(a,c,d,b);case "ol":return this.parseUL(a,c,d,b);case "li":return this.parseLI(a,c,d,b);case "dl":return this.parseDL(a,c,d,b);case "dt":return this.parseDT(a,c,d,b);case "dd":return this.parseDD(a,c,d,b);case "fieldset":return this.parseFieldset(a,
c,d,b);case "textset":return this.parseTextset(a,c,d,b);case "scenario":return this.parseScenario(a,c,d,b)}return null},parseEndPage:function(a){this.aligned||(a.stepPos(),a.skipUntilCRLF());throw"EndPage";},parseElement:function(a,c,d){if(this.forkset!=null&&this.forkset.hasNext())return this.forkset.yieldPage(c,d);try{var b=a.peekToken();d.seekTextPos=b.pos;d.seekTokenIndex=b.index;b=this.onParseElementBefore(a,c,d,b)}catch(e){return H(e),null}if(w.isEndPageToken(b))return this.parseEndPage(a,c,
d,b);if(w.isBlockToken(b))return this.parseBlockTag(a,c,d,b);return w.isForkPageToken(b)?(this.forktag=b.data.name,this.parseForkPageTag(a,c,d,b)):this.parseLine(a,c,d)},parsePage:function(a){var c=this.ctx.createPage(this.layout.direction,this.layout.width,this.layout.height,[]),d=this.args||{},b=0;s.copy(c,{no:this.ctx.seekPageNo,head:this.ctx.seekPageNo==0,spos:this.ctx.seekTextPos,ipos:this.ctx.seekTokenIndex,cpos:this.ctx.seekCharCount});s.copy(c,d||{});try{for(;;){var e=this.lexer.getPos(),
h=this.ctx.getSnap(),k=this.parseElement(this.lexer,this.layout,this.ctx);if(k==null)throw c.tail=true,c[this.layout.isVertical?"width":"height"]=b,this.finish=true,"EndPage";else{var n=f(this.layout,k);if(this.ctx.seekNextLine+n>this.layout.maxNextLine)throw"Overflow";this.ctx.seekNextLine+=n;b+=n;c.childs.push(k);if(this.ctx.seekNextLine==this.layout.maxNextLine)throw"EndPage";}}}catch(o){o=="Overflow"?(this.lexer.setPos(e),this.ctx.restoreSnap(h),this.ctx.seekNextLine=0):o=="EndPage"?this.ctx.seekNextLine=
0:H(o);if(this.pushBlocks.length>0)c.childs=c.childs.concat(this.pushBlocks),c[this.layout.isVertical?"width":"height"]+=l.fold(this.pushBlocks,0,function(a,b){return a+b.push_size}),this.pushBlocks=[];if(typeof this.aligned=="undefined")c.topicPath=q.clone(this.ctx.topicPath),this.ctx.seekPageNo++;if(this.edge)c.wrapWidth=c.width+(this.layout.isVertical?this.edge.sizeLineStep:this.edge.sizeCharStep),c.wrapHeight=c.height+(this.layout.isVertical?this.edge.sizeCharStep:this.edge.sizeLineStep),v.setEdgeProps(c,
this.edge);if(a&&a.capturePageText)a=c.spos,d=this.lexer.isEnd()?this.lexer.peekLastToken().pos:this.ctx.seekTextPos,c.text=this.lexer.getText().substring(a,d);return c}}};return a}(),K=function(){function c(){this.tags=[];this.ireaders=[]}c.prototype={getInlineReader:function(a){return this.ireaders[a]},pushInlineReader:function(a){var c=this.ireaders.length;this.ireaders.push(a);return c},clearInlineReaders:function(){this.ireaders=[]},pushTag:function(a){this.tags.push(a)},popTag:function(a){F.prototype.popTag.call(this,
a)},findTag:function(a){return l.find(this.tags,function(c){return c.name==a})}};return c}(),P=function(){function c(a,b){this.layout=a;this.ctx=typeof b!="undefined"?b:new K;this.handlers={}}var a=function(a,b){var c={};if(typeof b.scale!="undefined"){var e=Math.floor(b.scale*a.fontSize);c["font-size"]=e+"px";c["line-height"]=e+"px"}if(typeof b.family!="undefined")c["font-family"]=b.family;if(typeof b.weight!="undefined")c["font-weight"]=b.weight;if(typeof b.color!="undefined")c.color=b.color;return c},
f=function(a,b){var c=b.advanceSize;return{clear:"both",height:c+"px","line-height":c+"px"}},j=function(a,b){var c=Math.floor(b.fontSize*b.vscale),c={width:b.fontSize+"px",height:c+"px","line-height":c+"px"};typeof b["margin-prev-char"]!="undefined"&&(c[a.getCssProp("margin-prev-char")]=b["margin-prev-char"]+"px");typeof b["margin-next-char"]!="undefined"&&(c[a.getCssProp("margin-next-char")]=b["margin-next-char"]+"px");return c},g=function(a,b){var c=b.data,e=Math.floor(b.fontSize/2),d=typeof b["margin-prev-char"]!=
"undefined"?b["margin-prev-char"]:0,h=typeof b["margin-next-char"]!="undefined"?b["margin-next-char"]:0;c.length>2&&(h+=e*(c.length-2));c={"-webkit-transform":"rotate(90deg)","-webkit-transform-origin":"50% 50%","-moz-transform":"rotate(90deg)","-moz-transform-origin":"50% 50%","-o-transform":"rotate(90deg)","-o-transform-origin":"50% 50%",transform:"rotate(90deg)","transform-origin":"50% 50%"};c["margin-top"]=d+"px";c["margin-bottom"]=h+"px";return c},d=function(a,b){var c={"float":a.getCssProp("block-float"),
width:b.width+"px",height:b.height+"px",margin:0,padding:0};b["margin-prev-line"]&&(c[a.getCssProp("margin-prev-line")]=b["margin-prev-line"]+"px");return c},b=function(a,b){var c={"float":a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px","border-width":(b.border||0)+"px",margin:0,padding:0};b["margin-prev-line"]&&(c[a.getCssProp("margin-prev-line")]=b["margin-prev-line"]+"px");return c},e=function(a,b,c){a={width:"100%","font-size":c.fontSize+"px","line-height":c.fontSize+"px",
"float":"left","text-align":"center",padding:0};typeof c["margin-bottom"]!="undefined"&&(a["margin-bottom"]=c["margin-bottom"]+"px");typeof c["margin-top"]!="undefined"&&(a["margin-top"]=c["margin-top"]+"px");typeof c["text-align"]!="undefined"&&(a["text-align"]=c["text-align"]);return a},h=function(a,b,c){a={position:"absolute","font-size":c.fontSize+"px","line-height":c.fontSize+"px"};a["margin-left"]=c.position.x+"px";a["margin-top"]=c.position.y+"px";a["text-align"]="left";return a},B=function(a,
b){var c=a.isVertical?b.fontSize:b.textLineSize.height,c={display:"block","float":a.getCssProp("block-float"),"text-align":a.getCssProp("line-text-align"),"font-size":b.fontSize+"px",width:b.textLineSize.width+"px",height:b.textLineSize.height+"px","line-height":c+"px"};t.isIE&&a.isVertical&&(c.overflow="hidden");return c},n=function(a,b){var c=a.isVertical?b.fontSize:b.rubyLineSize.height;return{display:"block","float":a.getCssProp("block-float"),width:b.rubyLineSize.width+"px",height:b.rubyLineSize.height+
"px","line-height":c+"px"}},o=function(a,b){var c={display:"block",overflow:"visible","float":a.getCssProp("block-float"),width:b.width+"px",height:b.height+"px"};t.isMobileSafari&&(c["letter-spacing"]="-0.001em");return c},E=function(a,b){var c=o(a,b);b.attr["background-color"]&&(c["background-color"]=b.attr["background-color"]);c[a.isVertical?"height":"width"]="100%";return c},T=function(a,b){var c={"font-size":b.fontSize+"px","text-align":a.isVertical?"center":"left","line-height":b.fontSize+"px"};
a.isVertical||(c.height=b.fontSize+"px");c[a.getCssProp("margin-prev-char")]=b.textSpacePrevChar+"px";c[a.getCssProp("margin-next-char")]=b.textSpaceNextChar+"px";a.isVertical||(c["margin-top"]=Math.floor((b.height-b.fontSize)/2)+"px");b.attr.color&&(c.color=b.attr.color);return c},x=function(a,b){var c={display:"block","float":b["float"]||a.getCssProp("block-float"),width:b.width+"px","border-width":(b.border||0)+"px",height:b.height+"px"};b.size&&(c[a.getCssProp("page-size")]=b.size+"px");b["margin-prev-char"]&&
(c[a.getCssProp("margin-prev-char")]=b["margin-prev-char"]+"px");b["margin-next-char"]&&(c[a.getCssProp("margin-next-char")]=b["margin-next-char"]+"px");b["margin-prev-line"]&&(c[a.getCssProp("margin-prev-line")]=b["margin-prev-line"]+"px");b["margin-next-line"]&&(c[a.getCssProp("margin-next-line")]=b["margin-next-line"]+"px");b.forked&&(b.head||(c[a.getCssProp("border-prev-line")]="none"),b.tail||(c[a.getCssProp("border-next-line")]="none"));return c};c.prototype={getContext:function(){return this.ctx},
setOutputHandler:function(a,b){this.handlers[a]=b},callOutputHandler:function(a,b,c,e,d,h){return typeof this.handlers[a]!="undefined"?this.handlers[a](b,c,e,d,h):h},evalChar:function(a,b,c,e){return e.src?this.evalCharIcon(a,b,c,e):a.isVertical?this.evalCharVertical(a,b,c,e):this.evalCharHorizontal(a,b,c,e)},evalWord:function(a,b,c,e){return a.isVertical?this.evalWordVertical(a,b,c,e):e.data},evalTcy:function(a,b,c,e){return a.isVertical?e.data+"<br />":e.data},evalCharVertical:function(a,b,c,e){if(e.img)return this.evalCharImgVertical(a,
b,c,e);a=typeof e.cnv!="undefined"?e.cnv:e.data;return e.skana?m.wrap("div",{style:p.css({"font-size":e.fontSize+"px",overflow:"visible",position:"relative",top:"-0.2em",right:"-0.12em",height:e.advanceSize+"px","line-height":e.advanceSize+"px"})},a):a=="&nbsp;"?m.wrap("div",{style:p.css({"line-height":"0.5em",height:"0.5em"})},a):a+"<br />"},evalCharHorizontal:function(a,b,c,e){a=e.data==" "?"&nbsp;":e.data;return e.img&&e.hscale<1?m.wrap("span",{style:p.css({"letter-spacing":e.advanceSize-e.fontSize+
"px"})},a):a},evalCharIcon:function(a,b,c,e){b=[k.className.charIcon];e["class"]&&b.push(e["class"]);e=m.start("img",{"class":b.join(" "),width:e.width+"px",height:e.height+"px",style:p.css({}),src:e.src});return a.isVertical?e+"<br />":e},evalCharImgVertical:function(a,b,c,e){return m.wrap("div",{"class":k.className.charImg,style:p.css(f(a,e))},m.start("img",{src:r.ofImgSrc(e.img,e.color),style:p.css(j(a,e))}))},evalWordVertical:function(a,b,c,e){return t.isIE?m.wrap("div",{style:p.css({"writing-mode":"tb-rl",
"line-height":e.fontSize+"px","float":"left"})},e.data):m.wrap("div",{style:p.css({width:e.fontSize+"px",height:Math.floor(e.data.length*e.fontSize/2)+"px",overflow:"visible"})},m.wrap("div",{style:p.css(g(a,e))},e.data))},evalRubyBodyVert:function(a,b,c,e){a=e.data.length*e.fontSize;b=new z(e.data);a=new y({width:e.fontSize,height:a,fontSize:e.fontSize,enableRuby:false,disableTailSpace:true});c=new F(a);b=(new J(b,a)).parseLine(b,a,c);c=new K;return this.evalTextLineBody(a,c,e,b)},evalRubyBody:function(a,
b,c,e){return/vertical/.test(e.direction)?this.evalRubyBodyVert(a,b,c,e):e.data},evalRuby:function(a,b,c,e){return m.wrap("div",{"class":k.className.rubyText,style:p.css(h(a,c,e))},this.evalRubyBody(a,b,c,e))},evalCaption:function(a,b,c,d){return m.wrap("div",{"class":[k.className.caption,d.captionPos].join(" "),style:p.css(e(a,c,d))},q.escape(d.data))},evalStartLineTags:function(a,b,c){var e=this;return l.fold(b.tags,"",function(d,h){return h.name=="font"?d+e.evalFontStartBody(a,b,c,h):d+m.start(h.name,
h.attr)})},evalCloseLineTags:function(a,b,c){var e=this;return l.fold(b.tags,"",function(d,h){return h.name=="font"?d+e.evalFontEndBody(a,b,c,h):d+m.end(h.name)})},evalRubyLine:function(a,b,c,e){if(e.rubyLineSize.width==0||e.rubyLineSize.height==0)return"";var d=this,c=[k.className.rubyLine,a.direction].join("-");return m.wrap("div",{"class":[k.className.rubyLine,c].join(" "),style:p.css(n(a,e))},l.fold(e.rubyList,"",function(c,h){return c+d.evalRuby(a,b,e,h)}))},evalTextLineBody:function(a,b,c,e){var d=
this;return this.callOutputHandler("onCompleteTextLineBody",a,b,c,e,[this.evalStartLineTags(a,b,c,e),l.fold(e.childs,"",function(c,h){return c+d.evalElement(a,b,e,h)}),this.evalCloseLineTags(a,b,c,e)].join(""))},evalTextLine:function(a,b,c,e){var d=[k.className.textLine,a.direction].join("-");return m.wrap("div",{"class":[k.className.textLine,d].join(" "),style:p.css(B(a,e))},this.evalTextLineBody(a,b,c,e))},evalLineSet:function(a,b,c,e){return a.enableRuby?[this.evalRubyLine(a,b,c,e),this.evalTextLine(a,
b,c,e)].join(""):this.evalTextLine(a,b,c,e)},evalLine:function(a,b,c,e){return m.wrap("div",{"class":k.className.line,style:p.css(o(a,e))},this.evalLineSet(a,b,c,e))},evalLabelLine:function(a,b,c,e){return m.wrap("div",{"class":k.className.labelLine,style:p.css(E(a,e))},m.wrap("div",{"class":k.className.labelLineBody,style:p.css(T(a,e))},this.evalTextLineBody(a,b,c,e)))},evalImgBody:function(a,b,c,e){a=b.findTag("a");e=m.start("img",{id:e.id,src:e.src,width:e.width,height:e.height,style:p.css({"border-width":(e.border||
0)+"px",width:e.width+"px",height:e.height+"px"})});return a!=null?m.wrap("a",a.attr,e):e},evalImg:function(a,b,c,e){return m.wrap("div",{"class":k.className.img,style:p.css(d(a,e))},this.evalImgBody(a,b,c,e))},evalBlock:function(a,c,e,d){if(d.name=="img")return this.evalImg(a,c,e,d);a={id:d.id,"class":k.className.blockElement,style:p.css(b(a,d))};if(d.name=="iframe")a.src=d.src,a.frameborder=d.frameborder,a.width=d.width,a.height=d.height;else if(d.name=="textarea")a.onclick=d.onclick;else if(d.name==
"ibox")d.name="div",a["class"]=[a["class"],k.className.inlineBox].join(" ");return m.wrap(d.name,a,d.content)},evalInlineReader:function(a,c,e,d){c=c.pushInlineReader(d);return m.wrap("div",{id:d.id,"class":[k.className.inlineReader,"ireader-"+c].join(" "),style:p.css(b(a,d))},"")},evalLinkStart:function(a,b,c,e){a=e.attr;a.href=a.href||"";if(a.href.substring(0,1)=="#")a["class"]=k.className.tocLink;b.pushTag(e);return m.start(e.name,e.attr)},evalLinkEnd:function(a,b,c,e){a=e.name.substring(1);b.popTag(a);
return m.end(a)},evalBoldStart:function(a,b,c,e){b.pushTag(e);return m.start(e.name,e.attr)},evalBoldEnd:function(a,b,c,e){a=e.name.substring(1);b.popTag(a);return m.end(a)},evalFontStart:function(a,b,c,e){b.pushTag(e);return this.evalFontStartBody(a,b,c,e)},evalFontStartBody:function(b,c,e,d){c={style:p.css(a(b,d.attr))};d.attr["class"]&&(c["class"]=d.attr["class"]);return m.start(b.isVertical?"div":"span",c)},evalFontEnd:function(a,b,c,e){b.popTag("font");return this.evalFontEndBody(a,b,c,e)},evalFontEndBody:function(a){return a.isVertical?
m.end("div"):m.end("span")},evalTag:function(a,b,c,e){e=e.data;switch(e.name){case "a":return this.evalLinkStart(a,b,c,e);case "/a":return this.evalLinkEnd(a,b,c,e);case "b":case "strong":return this.evalBoldStart(a,b,c,e);case "/b":case "/strong":return this.evalBoldEnd(a,b,c,e);case "font":return this.evalFontStart(a,b,c,e);case "/font":return this.evalFontEnd(a,b,c,e)}return""},evalElement:function(a,b,e,d){switch(d.type){case "char":return this.evalChar(a,b,e,d);case "rb":return this.evalChar(a,
b,e,d);case "word":return this.evalWord(a,b,e,d);case "tcy":return this.evalTcy(a,b,e,d);case "line":return this.evalLine(a,b,e,d);case "label-line":return this.evalLabelLine(a,b,e,d);case "caption":return this.evalCaption(a,b,e,d);case "ruby":return this.evalRuby(a,b,e,d);case "block":return this.evalBlock(a,b,e,d);case "ireader":return this.evalInlineReader(a,b,e,d);case "tag":return this.evalTag(a,b,e,d);case "page":return(new c(new y({width:d.width,height:d.height,fontSize:a.fontSize,direction:d.direction||
a.direction}),b)).evalPage(d)}return""},evalPage:function(a,b){var c=this,e=[];s.copy(a,b||{});a.forked?e.push(k.className.forkedPage):a.aligned?e.push(k.className.alignedPage):e.push(k.className.page);typeof a["class"]!="undefined"&&e.push(a["class"]);a.syntax&&this.setOutputHandler("onCompleteTextLineBody",O[a.syntax].editLine);return m.wrap("div",{"class":e.join(" "),style:p.css(x(this.layout,a))},l.fold(a.childs,"",function(b,e){return b+c.evalElement(c.layout,c.ctx,a,e)}))}};return c}(),O={js:{editLine:function(c,
a,f,j,g){return c.isVertical?g:g.replace(/[^:\"\'](\/\/.+)$/,"<span class='kw-cmt'>$1</span>").replace(/(\/\*[^\*]+\*\/)/,"<span class='kw-cmt'>$1</span>").replace(/(\"[^\"]+\")/g,"<span class='kw-string'>$1</span>")}},html:{editLine:function(c,a,f,j,g){return c.isVertical?void 0:O.js.editLine(c,a,f,j,g)}}},Q=function(){function c(a,c){this.lexer=new z(a);this.parser=new J(this.lexer,c);this.evaluator=new P(c)}c.prototype={hasNext:function(){return this.parser.hasNext()},getParser:function(){return this.parser},
getEvaluator:function(){return this.evaluator},parsePage:function(){return this.parser.parsePage()},evalPage:function(a,c){return this.evaluator.evalPage(a,c)},yieldPage:function(a){return this.evalPage(this.parsePage(),a)}};return c}(),R=function(){function c(a,b){this.dom=document.createElement("div");this.dom.className=d.className.screen;this.dom_s=this.dom.style;this.dom_s.width=a+"px";this.dom_s.height=b+"px";this.dom_s.margin=[d.screenSpaceTB+"px",d.screenSpaceLR+"px"].join(" ");this.dom_s.overflow=
"hidden";this.dom.innerHTML="<h2 class='"+d.className.loadingText+"'>LOADING...</h2>"}function a(a,b,c,f){var j=this;this.dom=document.createElement("div");this.dom.className=d.className.pager;this.dom_s=this.dom.style;this.dom_s.verticalAlign="middle";this.dom_s.fontSize=d.pager.fontSize+"px";this.dom_s.textAlign="center";this.dom_s.height=d.pager.height+"px";this.dom_s.lineHeight=d.pager.height+"px";this.dom_s.margin=d.pager.marginVert+"px 0";var g=document.createElement("a"),k=g.style;g.href="#btnNext";
g.className=d.className.pagerNext.join(" ");g.onclick=function(){c();return false};k.width=d.pager.btnWidth+"px";var l=document.createElement("a"),m=l.style;l.href="#btnPrev";l.className=d.className.pagerPrev.join(" ");l.onclick=function(){b();return false};m.width=d.pager.btnWidth+"px";var D=document.createElement("span");D.className=d.className.pagerStatus;D.style.width=d.pager.statusWidth+"px";this.curPage=document.createElement("input");this.curPage.className=d.className.pagerCurPage;this.curPage.type=
"text";this.curPage.value="0";this.curPage.style.width=d.pager.curPageInputWidth+"px";this.curPage.onkeypress=u.onkeypress(function(a){var b=j.getPageNo();a==13&&f(b)});this.pageSlash=document.createElement("span");this.pageSlash.innerHTML="/";this.pageSlash.style.margin="0 10px";this.totalPage=document.createElement("span");this.totalPage.className=d.className.pagerTotalPage;D.appendChild(this.curPage);D.appendChild(this.pageSlash);D.appendChild(this.totalPage);a.indexOf("vertical")>=0?(g.innerHTML=
d.pager.nextLinkTextVert,l.innerHTML=d.pager.prevLinkTextVert,k.marginRight="16px",m.marginLeft="16px",this.dom.appendChild(g),this.dom.appendChild(D),this.dom.appendChild(l)):(g.innerHTML=d.pager.nextLinkTextHori,l.innerHTML=d.pager.prevLinkTextHori,m.marginRight="16px",k.marginLeft="16px",this.dom.appendChild(l),this.dom.appendChild(D),this.dom.appendChild(g))}function f(){this.dom=document.createElement("div");this.dom.className=d.className.footer;this.dom_s=this.dom.style;this.dom_s.textAlign=
"right";this.dom_s.marginRight=d.defFontSize+"px";this.dom_s.marginTop=d.footer.marginVert+"px";this.dom_s.height=d.footer.height+"px";this.dom_s.lineHeight=d.footer.height+"px";var a=document.createElement("div");a.className=d.className.copy;a.style.fontSize="0.9em";a.innerHTML="powered by <a target='_blank' href='https://code.google.com/p/nehan/'>nehan</a> layout engine.";this.dom.appendChild(a)}function j(a,b){this.reader=a;this.offset=0;this.keyword=b}function g(a){this.nospace=typeof a.nospace!=
"undefined"?a.nospace:false;this.isinline=typeof a.isinline!="undefined"?a.isinline:false;this.nopager=typeof a.nopager!="undefined"?a.nopager:false;this.border=typeof a.border!="undefined"?a.border:k.layout.readerBorder;this.width=a.width||d.defOuterWidth;this.height=a.height||d.defOuterHeight;this.screenWidth=this.width-d.screenSpaceLR*2;this.screenHeight=this.height-d.screenSpaceTB*2;this.nopager==false&&(this.screenHeight-=d.pager.height+d.pager.marginVert*2);this.isinline==false&&(this.screenHeight-=
d.footer.height+d.footer.marginVert);this.pages=[];this.caches=[];this.ireaders=[];this.bookmarks=[];this.pageNo=this.progress=0;this.complete=false;this.direction=a.direction||d.defDirection;this.text=a.text||"no text";this.theme=I[a.theme]||null;this.syntax=a.syntax||"";this.className=a.className;this.pageLayout=new y({direction:this.direction,theme:this.theme,width:this.screenWidth,height:this.screenHeight,fontSize:a.fontSize||d.defFontSize,leadingRate:a.leadingRate||d.defLeadingRate});this.generator=
new Q(this.text,this.pageLayout);this.onStart=a.onStart||function(){};this.onReady=a.onReady||function(){};this.onProgress=a.onProgress||function(){};this.onComplete=a.onComplete||function(){};this.onWritePageStart=a.onWritePageStart||function(){};this.onWritePageEnd=a.onWritePageEnd||function(){};this.onWriteLastNext=a.onWriteLastNext||function(){};this.onWriteFirstPrev=a.onWriteFirstPrev||function(){}}var d={defDirection:"horizontal",defFontSize:20,defOuterWidth:600,defOuterHeight:400,defLeadingRate:1.8,
screenSpaceTB:20,screenSpaceLR:32,maxSearchResult:10,maxSearchExcerptLen:20,className:{targetMarkup:"nehan3-pagerize",screenWrap:"nehan3-pagerize-screen-wrap",screen:"nehan3-pagerize-screen",pager:"nehan3-pagerize-pager",footer:"nehan3-pagerize-footer",copy:"nehan3-pagerize-copyright",pagerStatus:"nehan3-pagerize-pager-status",pagerCurPage:"nehan3-pagerize-pager-cur-page",pagerTotalPage:"nehan3-pagerize-pager-total-page",pagerNext:["gn-button","nehan3-pagerize-pager-next"],pagerPrev:["gn-button",
"nehan3-pagerize-pager-prev"],loadingText:"nehan3-pagerize-loading-text"},pager:{fontSize:16,height:30,marginVert:5,btnWidth:80,statusWidth:140,curPageInputWidth:30,nextLinkTextVert:"&laquo; NEXT",prevLinkTextVert:"PREV &raquo;",nextLinkTextHori:"NEXT &raquo;",prevLinkTextHori:"&laquo; PREV"},footer:{height:20,marginVert:5},system:{parsingLoop:20,parsingLoopIE:10,parsingSleepIE:10}},b={_findTargetNodes:function(){var a=document.getElementsByTagName("pre");return l.filter(a,function(a){return a.className.indexOf(d.className.targetMarkup)>=
0})},parseOpt:function(a){a=a||{};s.init(a,{width:d.defOuterWidth,height:d.defOuterHeight,fontSize:d.defFontSize,direction:d.defDirection},a);return a},map:function(a){var a=this.parseOpt(a),b=this._findTargetNodes();l.iter(b,function(b){var c=b.className,d=q.clone(a);d.text=b.innerHTML;if(c.indexOf("lp-horizontal")>=0)d.direction="horizontal";else if(c.indexOf("lp-vertical")>=0)d.direction="vertical";(new g(d)).start(b)})},createReader:function(a){a=this.parseOpt(a);return new g(a)}};c.prototype=
{getDOM:function(){return this.dom},getInlineReaderDOMs:function(){return l.filter(this.dom.getElementsByTagName("div"),function(a){return a.className&&a.className.indexOf(k.className.inlineReader)>=0?true:false})},update:function(a){this.dom.innerHTML=a}};a.prototype={getDOM:function(){return this.dom},getPageNo:function(){return Math.max(0,parseInt(this.curPage.value)-1)},setPageNo:function(a){this.curPage.value=a},setPageCount:function(a){this.totalPage.innerHTML=a}};f.prototype={getDOM:function(){return this.dom}};
j.prototype={hasNext:function(){return this.offset>=0},getNext:function(){for(var a=this.reader,b=this.reader.getText(),c=this.keyword,f=[],g=0;g<d.maxSearchResult;g++){this.offset=b.indexOf(c,this.offset+1);if(this.offset<0)break;f.push(this.offset)}var j=function(a){return a.replace(RegExp("("+c+")","g"),function(a,b){return"<strong>"+q.escape(b)+"</strong>"})};return l.map(f,function(f){var g=a.findPageNo(f),k=a.getSourceText(g),k=d.maxSearchExcerptLen,k=b.substring(f,f+c.length+k),k=k.replace(/<rt>[^<]+<\/rt>/g,
""),k=k.replace(/<[^>]+>/g,""),k=q.escape(k),k=j(k);return{spos:f,pageNo:g,text:k}})}};g.prototype={start:function(a){this.setupUI(a);this.complete=false;this.progress=0;this.onStart(this);this.addPage(this.parsePage());this.writePage(0);this.onReady(this);if(this.pager)this.parsePageBg();else this.onComplete(this)},setupUI:function(b){var h=this;b.innerHTML="";this.dom=b;this.dom.className=[d.className.screenWrap,this.dom.className,this.className].join(" ");this.dom_s=b.style;this.dom_s.overflow=
"hidden";this.dom_s.display="block";this.dom_s.width=this.width+"px";this.dom_s.height=this.height+"px";this.dom_s.borderWidth=this.border+"px";this.screen=new c(this.screenWidth,this.screenHeight);this.dom.appendChild(this.screen.getDOM());if(this.nopager==false)this.pager=new a(this.direction,function(){h.writePrev()},function(){h.writeNext()},function(a){h.writePage(a)}),this.dom.appendChild(this.pager.getDOM());if(this.isinline==false)this.footer=new f,this.dom.appendChild(this.footer.getDOM())},
resume:function(a){this.setupUI(a);this.setPageCount(this.pages.length);this.writePage(this.pageNo)},parsePage:function(){var a=this.generator.parsePage();a.syntax=this.syntax;return a},getGenerator:function(){return this.generator},getText:function(){return this.text},getDirection:function(){return this.direction},getTocs:function(){return this.generator.getParser().getContext().getTocs()},getPageNo:function(){return this.pageNo},getTotalPageCount:function(){return this.pages.length},getDOM:function(){return this.dom},
getPageJson:function(a){return this.pages[a]||null},getTopicPath:function(a){a=this.getPageJson(a);return a!=null?a.topicPath:null},getTopicPathTitle:function(a){return l.map(a,function(a){return a.title}).join("/")},makeBookmark:function(a){a=this.getPageJson(a);return a==null?null:this.getTopicPathTitle(a.topicPath)},setBookmark:function(a){var b=this.makeBookmark(a);return this.bookmarks[a]=b},deleteBookmark:function(a){this.bookmarks[a]=null},getBookmarks:function(){return this.bookmarks},getPageCache:function(a){return this.caches[a]||
null},setPageCache:function(a,b){this.caches[a]=b},setPageNo:function(a){this.pager&&this.pager.setPageNo(a)},setPageCount:function(a){this.pager&&this.pager.setPageCount(a)},getSourceText:function(a){var b=this.getPageJson(a),a=this.getPageJson(Math.max(a+1,this.pages.length-1));return b==null||a==null?"":this.text.substring(b.spos,a.spos)},findPageNo:function(a){for(var b=0,c=this.pages.length;b<c;b++){var d=this.pages[b].spos;if(d>a)return Math.max(0,b-1);else if(d==a)return b}return Math.max(0,
c-1)},searchKeyword:function(a){return new j(this,a)},getSeekPos:function(a){return this.pages[a]?(a=this.pages[a],{cpos:a.cpos,spos:a.spos}):null},addPage:function(a){this.pages.push(a);return a},parsePageBg:function(){for(var a=null,b=null,c=t.isIE?d.system.parsingLoopIE:d.system.parsingLoop,f=0;f<c;f++){if(!this.generator.hasNext()){this.setPageCount(this.pages.length);this.complete=true;this.onComplete(this);return}a=b;b=this.addPage(this.parsePage());if(a!=null&&b!=null&&a.no==b.no)return}if(b)this.progress=
Math.floor(this.generator.getParser().getPercent(b)),this.setPageCount("("+this.progress+"%)"),this.onProgress(this,this.progress,this.pages.length);var g=this;setTimeout(function(){g.parsePageBg()},t.isIE?d.system.parsingSleepIE:0)},getInlineReaderFromCache:function(a,b){return this.ireaders[a]&&this.ireaders[a][b]?this.ireaders[a][b]:null},cacheInlineReader:function(a,b,c){this.ireaders[a]||(this.ireaders[a]=[]);this.ireaders[a][b]=c},setupTocLinks:function(){var a=this,b=this.screen.getDOM().getElementsByTagName("a");
l.iter(b,function(b){if(b.className==k.className.tocLink){var c=b.href.split("#");if(c.length>0){var d=c[1];b.onclick=function(){a.writePageByTocId(d);return true}}}})},writeInlineReaders:function(a,b){var c=this,d=this.generator.getEvaluator().getContext();l.iter(b,function(b){if(b.className.match(/ireader-([\d]+)/)){var h=parseInt(RegExp.$1),f=c.getInlineReaderFromCache(a,h);f!=null?f.resume(b):(f=d.getInlineReader(h),f=new g({text:f.content,className:f["class"],direction:f.direction,fontSize:f.fontSize,
width:f.width,height:f.height,theme:f.theme,syntax:f.syntax,border:f.border,nopager:f.nopager,isinline:true}),f.child=true,f.start(b),c.cacheInlineReader(a,h,f))}})},writePageByTocId:function(a){var b=l.find(this.getTocs(),function(b){return b.id==a});b!=null&&this.writePage(b.pageNo)},writePageWithCache:function(a){var b=this.getPageJson(a);if(b!=null){var c=this.getPageCache(a);c==null&&(c=this.generator.evalPage(b),this.setPageCache(a,c));this.setPageNo(a+1);this.screen.update(c);this.writeInlineReaders(a,
this.screen.getInlineReaderDOMs());this.setupTocLinks()}},writePage:function(a){(a>=this.pages.length||a<0)&&alert("pageNo("+a+") is not available for this book");this.pageNo=a;this.onWritePageStart(this,a);this.writePageWithCache(a);this.onWritePageEnd(this,a)},writeNext:function(){if(this.pageNo<this.pages.length-1)this.writePage(this.pageNo+1);else this.onWriteLastNext(this)},writePrev:function(){if(this.pageNo>0)this.writePage(this.pageNo-1);else this.onWriteFirstPrev(this)}};b.pgconfig=d;return b}(),
U=function(){var c=function(a,b,c){var f=document.createElement("a");f.href="#"+a;f.innerHTML=b;f.onclick=function(){c.writePage(a);return true};return f},a=function(a,b,e){var f=document.createElement("table"),g=document.createElement("thead"),j=document.createElement("tr"),k=document.createElement("th"),l=document.createElement("th"),m=document.createElement("th"),x=document.createElement("tbody");f.className="nehan3-book-bmark-table";f.style.borderCollapse="collapse";k.innerHTML="topic path";l.innerHTML=
"page";m.innerHTML="delete";j.appendChild(k);j.appendChild(l);j.appendChild(m);g.appendChild(j);f.appendChild(g);f.appendChild(x);a.appendChild(f);var p=function(a,b){var d=document.createElement("tr"),f=document.createElement("td"),h=document.createElement("td"),g=document.createElement("td"),j=c(a,b,e),k=document.createElement("a");k.href="#delete";k.innerHTML="delete";k.onclick=function(){e.deleteBookmark(a);x.removeChild(d);return false};f.appendChild(j);h.innerHTML=a+1;g.appendChild(k);d.appendChild(f);
d.appendChild(h);d.appendChild(g);return d};b.onclick=function(){var a=e.getPageNo(),b=e.setBookmark(a);bmark!=null&&(a=p(a,b),x.appendChild(a));return false}},f=function(a,b,c,f){var g=function(a){a!=""&&(a=f.searchKeyword(a),j(c,f,a))};a.onkeypress=u.onkeypress(function(b){b==13&&g(a.value)});b.onclick=function(){g(a.value);return false}},j=function(a,b,c){a.innerHTML="";a.style.overflow="hidden";var f=c.getNext();if(f.length==0)a.innerHTML="<p>not found</p>";else{var g=function(){var f=document.createElement("p"),
g=document.createElement("a");g.href="#more";g.innerHTML="more result";g.onclick=function(){j(a,b,c);return false};f.appendChild(g);return f},k=function(a){var c=document.createElement("tr"),d=document.createElement("td"),e=document.createElement("a");e.innerHTML="p"+(a.pageNo+1);e.href="#"+a.pageNo;e.onclick=function(){b.writePage(a.pageNo);return false};d.appendChild(e);e=document.createElement("td");e.innerHTML=a.text;c.appendChild(d);c.appendChild(e);return c},m=function(){var a=document.createElement("table"),
b=document.createElement("thead"),c=document.createElement("tr"),d=document.createElement("th");d.innerHTML="page";var e=document.createElement("th");e.innerHTML="text";c.appendChild(d);c.appendChild(e);b.appendChild(c);a.appendChild(b);return a}(),p=document.createElement("tbody");m.appendChild(p);l.iter(f,function(a){p.appendChild(k(a))});f=function(){var b=document.createElement("p"),c=document.createElement("a");c.innerHTML="clear search result";c.href="#clear";c.onclick=function(){a.innerHTML=
"";return false};b.appendChild(c);return b}();a.appendChild(f);a.appendChild(m);c.hasNext()&&(g=g(),a.appendChild(g))}},g=function(a,b,c){a.innerHTML="";c=b.getTopicPath(c);if(c!=null){var f=Math.max(0,c.length-1);l.iteri(c,function(c,e){var g=document.createElement("a");g.innerHTML=e.title;g.href="#"+e.pageNo;g.onclick=function(){b.writePage(e.pageNo);return false};a.appendChild(g);if(c!=f)g=document.createElement("span"),g.innerHTML="/",g.style.margin="0 0.5em",a.appendChild(g)})}};return{start:function(d){var b=
new Date,e=0,h="",j=document.getElementById(d.ui.topicPathId||"topic-path"),l=document.getElementById(d.ui.tocId||"toc"),m=document.getElementById(d.ui.searchInputId||"search-input"),p=document.getElementById(d.ui.searchBtnId||"search-btn"),r=document.getElementById(d.ui.searchResultId||"search-result"),q=document.getElementById(d.ui.bookBodyId||"book-body"),s=d.text||(q?q.innerHTML:"body text not found"),v=document.getElementById(d.ui.bmarkId||"bmark"),w=document.getElementById(d.ui.bmarkBtnId||
"bmark-btn");q.innerHTML="";s=R.createReader({text:s,direction:d.direction||"horizontal",width:d.width||700,height:d.height||600,fontSize:d.fontSize||18,onStart:function(a){if(location.href.match("#")){var b=location.href.split("#")[1];isNaN(b)?h=b:e=parseInt(b)}if(d.onStart)d.onStart(a)},onComplete:function(g){var j=(new Date-b)/1E3;if(l){var q=g.getTocs(),s=document.createElement("ul"),t=s,u=null;s.className="nehan3-book-toc-root";for(var y=0,B=q.length;y<B;y++){var A=q[y],x=document.createElement("li"),
z=c(A.pageNo,A.title||"no title",g);x.appendChild(z);if(u==null)t.appendChild(x);else if(A.level==u.level)t.appendChild(x);else if(A.level>u.level){var u=A.level,z=document.createElement("ul"),C=k.tags.toc;z.className=["nehan3-book-toc-level",C[u%C.length]].join("-");ul=z;ul.appendChild(x);t.appendChild(ul);t=ul}else A.level<u.level&&(t=A.level<=0?s:t.parentNode,t.appendChild(x));u=A}l.appendChild(s)}m&&p&&r&&f(m,p,r,g);v&&w&&a(v,w,g);if(d.onComplete)d.onComplete(g,j);e>0?g.writePage(e):h!=""&&g.writePageByTocId(h)},
onProgress:function(a,b,c){if(d.onProgress)d.onProgress(a,b,c)},onWritePageStart:function(a,b){window.scroll(0,0);if(d.onWritePageStart)d.onWritePageStart(a,b)},onWritePageEnd:function(a,b){g(j,a,b);if(d.onWritePageEnd)d.onWritePageEnd(a,b)}});if(d.onBeforeStart)d.onBeforeStart(s);s.start(q)}}}();Nehan3.version="3.0.6-pre";Nehan3.env=t;Nehan3.config=k;Nehan3.Pagerize=R;Nehan3.Book=U;Nehan3.Util=q;Nehan3.Closure=u;Nehan3.Args=s;Nehan3.List=l;Nehan3.Attr=p;Nehan3.Tag=m;Nehan3.Token=w;Nehan3.Char=r;
Nehan3.Word=L;Nehan3.CharImgColor=M;Nehan3.Lexer=N;Nehan3.BufferedLexer=z;Nehan3.Layout=y;Nehan3.Theme=I;Nehan3.ParserContext=F;Nehan3.DocumentParser=J;Nehan3.EvalContext=K;Nehan3.NehanEvaluator=P;Nehan3.PageGenerator=Q})();



