/*
 source : nehan2.js
 version : 1.24
 site : http://tategakibunko.mydns.jp/
 blog : http://tategakibunko.blog83.fc2.com/

 Copyright (c) 2010, Watanabe Masaki <lambda.watanabe@gmail.com>
 licenced under MIT licence.

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
*/
var Nehan;Nehan||(Nehan={});
(function(){function l(a,b,c){this.text=a;this.length=b;this.eof=c;this.pos=0}function n(a){this.stream=a}function o(a){g.readOption(this,{direction:"vertical",width:400,height:300,fontSize:16,fontColor:"000000",linkColor:"0000FF",charImgRoot:"http://nehan.googlecode.com/hg/char-img/",nextLineOffsetRate:1.8},a);this.init()}function q(a){this.lineTokens=[];this.nextLineTokens=[];this.rubyTokens=[];this.nextRubyTokens=[];this.activeTags={};this.tagStack=[];this.fontStack=[];this.indentStack=[];this.dotTokens=
[];this.repushTokenStack=[];this.curFontScale=1;this.curFontColor=a.fontColor;this.curFontSize=a.fontSize;this.curFontSizeHalf=a.fontSizeHalf;this.curIndent={before:0,after:0};this.seekNextChar=this.seekNextLine=this.curCharCount=this.saveSeekPos=this.curPageNo=this.curBorderSize=0;this.pageHtml="";this.pageHeadPos=0}function e(a,b){this.lexer=a;this.layout=b;this.context=new q(b);this.parseEnd=false;this.elementHandler=[];this.tocTable=[]}function k(a,b,c){this.layout=a;this.lexer=b;this.parser=
c;this.stream=this.lexer.stream}function i(a,b,c){this.layout=new o(a);this.lexer=c?new n(new l(b,c,b.length>=c)):new n(new l(b,b.length,true));this.parser=new e(this.lexer,this.layout);this.parserProxy=new k(this.layout,this.lexer,this.parser);this.pageHeadPos=[{spos:0,cpos:0}];this.resuming=false;this.cache=[];this.restoreContext=null}function s(a,b){this.node=a;this.nodeNo=b;this.groupName="nehan-layout-group-"+b;this.order=0;this.isEnd=false;this.direction="vertical";this.fontSize=16;this.fontColor=
"000000";this.linkColor="0000FF";this.width=400;this.height=300;this.init(a.className)}function r(a,b){this.grids=[];this.groupName=a;this.opt=b}var t={init:function(){this.browser=this.searchString(this.dataBrowser)||"An unknown browser";this.version=this.searchVersion(navigator.userAgent)||this.searchVersion(navigator.appVersion)||"an unknown version";this.OS=this.searchString(this.dataOS)||"an unknown OS"},searchString:function(a){for(var b=0;b<a.length;b++){var c=a[b].string,d=a[b].prop;this.versionSearchString=
a[b].versionSearch||a[b].identity;if(c){if(c.indexOf(a[b].subString)!=-1)return a[b].identity}else if(d)return a[b].identity}},searchVersion:function(a){var b=a.indexOf(this.versionSearchString);return b==-1?void 0:parseFloat(a.substring(b+this.versionSearchString.length+1))},dataBrowser:[{string:navigator.userAgent,subString:"Chrome",identity:"Chrome"},{string:navigator.userAgent,subString:"OmniWeb",versionSearch:"OmniWeb/",identity:"OmniWeb"},{string:navigator.vendor,subString:"Apple",identity:"Safari",
versionSearch:"Version"},{prop:window.opera,identity:"Opera"},{string:navigator.vendor,subString:"iCab",identity:"iCab"},{string:navigator.vendor,subString:"KDE",identity:"Konqueror"},{string:navigator.userAgent,subString:"Firefox",identity:"Firefox"},{string:navigator.vendor,subString:"Camino",identity:"Camino"},{string:navigator.userAgent,subString:"Netscape",identity:"Netscape"},{string:navigator.userAgent,subString:"MSIE",identity:"Explorer",versionSearch:"MSIE"},{string:navigator.userAgent,subString:"Gecko",
identity:"Mozilla",versionSearch:"rv"},{string:navigator.userAgent,subString:"Mozilla",identity:"Netscape",versionSearch:"Mozilla"}],dataOS:[{string:navigator.platform,subString:"Win",identity:"Windows"},{string:navigator.platform,subString:"Mac",identity:"Mac"},{string:navigator.userAgent,subString:"iPhone",identity:"iPhone/iPod"},{string:navigator.platform,subString:"Linux",identity:"Linux"}]};t.init();var p={init:function(){var a=t.browser.toLowerCase(),b=t.version,c=t.OS;this.isIE=a=="explorer";
this.isWin=c=="Windows";this.isMac=c=="Mac";this.isIPhone=navigator.platform=="iPhone";this.isIPad=navigator.platform=="iPad";this.isIPod=navigator.platform=="iPod";this.isMobileSafari=this.isIPhone||this.isIPad||this.isIPod;this.canTransform=a=="chrome"?true:a=="safari"?true:a=="firefox"&&b>=3.5?true:a=="opera"?true:this.isIE&&b>=6?true:false}};p.init();var u={RG:[0,36,73,109,146,182,219,255],B:[0,85,170,255],getRGB:function(a){return{r:parseInt(a.substring(0,2),16),g:parseInt(a.substring(2,4),16),
b:parseInt(a.substring(4,6),16)}},findNear:function(a,b){if(a==0||a==255)return a;for(var c=256,d=0,j=0;j<b.length;j++){var f=Math.abs(a-b[j]);f<c&&(c=f,d=b[j])}return d},get:function(a){var b=this.getRGB(a.replace("#","")),c=function(a){return a.length<=1?"0"+a:a},a=c(this.findNear(b.r,this.RG).toString(16)),d=c(this.findNear(b.g,this.RG).toString(16)),b=c(this.findNear(b.b,this.B).toString(16));return(a+d+b).toUpperCase()}},g={filenameConcat:function(a,b){a=a==""?"":a.slice(-1)=="/"?a:a+"/";b=b==
""?"":b[0]=="/"?b.substring(1,b.length):b;return a+b},readOption:function(a,b,c){for(prop in b)a[prop]=typeof c[prop]=="undefined"?b[prop]:c[prop]},deepCopy:function(a){var b;if(typeof a=="object")if(a instanceof Array){b=[];for(var c=0;c<a.length;c++)b[c]=this.deepCopy(a[c])}else for(prop in b={},a)b[prop]=this.deepCopy(a[prop]);else b=a;return b},cutQuote:function(a){return a.replace(/\"/g,"").replace(/\'/g,"")},inlineAttr:function(a){var b="";for(prop in a)a[prop]!=""&&(b+=" "+prop+"='"+a[prop]+
"'");return b},inlineCss:function(a){var b="";for(prop in a)b+=prop+":"+a[prop]+";";return b},tagStart:function(a,b,c){a="<"+a;b&&(a+=this.inlineAttr(b));a+=c?"/>":">";return a},tagWrap:function(a,b,c){return this.tagStart(a,b,false)+c+"</"+a+">"},setRadius:function(a,b,c,d){c+="px";d["-moz-border-radius-"+a+b]=c;d["-khtml-border-radius-"+a+b]=c;d["-webkit-border-"+a+"-"+b+"-radius"]=c}},w={get:function(a){switch(a){case "\u300c":case "\uff62":return{imgname:"kakko1",hscale:0.5,kind:"img-char"};case "\u300d":case "\uff63":return{imgname:"kakko2",
hscale:0.5,kind:"img-char"};case "\u300e":return{imgname:"kakko3",hscale:0.5,kind:"img-char"};case "\u300f":return{imgname:"kakko4",hscale:0.5,kind:"img-char"};case "\uff08":case "(":case "\uff5b":case "{":return{imgname:"kakko5",hscale:0.5,kind:"img-char"};case "\uff09":case ")":case "\uff5d":case "}":return{imgname:"kakko6",hscale:0.5,kind:"img-char"};case "\uff1c":case "<":case "\u3008":return{imgname:"kakko7",hscale:0.5,kind:"img-char"};case "\uff1e":case ">":case "\u3009":return{imgname:"kakko8",
hscale:0.5,kind:"img-char"};case "\u300a":case "\u226a":return{imgname:"kakko9",hscale:0.5,kind:"img-char"};case "\u300b":case "\u226b":return{imgname:"kakko10",hscale:0.5,kind:"img-char"};case "\uff3b":case "\u3014":case "[":return{imgname:"kakko11",hscale:0.5,kind:"img-char"};case "\uff3d":case "\u3015":case "]":return{imgname:"kakko12",hscale:0.5,kind:"img-char"};case "\u3010":return{imgname:"kakko17",hscale:0.5,kind:"img-char"};case "\u3011":return{imgname:"kakko18",hscale:0.5,kind:"img-char"};
case "\uff1a":case ":":return{imgname:"tenten",hscale:0.5,kind:"img-char"};case "\u3002":case "\uff61":return{imgname:"kuten",hscale:0.5,kind:"img-char"};case "\uff0e":case ".":return{imgname:"period",hscale:1,kind:"img-char"};case "\u3001":case "\uff64":case ",":case "\uff0c":return{imgname:"touten",hscale:0.5,kind:"img-char"};case "\uff5e":case "\u301c":return{imgname:"kara",hscale:1,kind:"img-char"};case "\u2026":return{imgname:"mmm",hscale:1,kind:"img-char"};case "\u2025":return{imgname:"mm",
hscale:1,kind:"img-char"};case "\u301d":return{imgname:"dmn1",hscale:1,kind:"img-char"};case "\u301f":return{imgname:"dmn2",hscale:1,kind:"img-char"};case "\uff1d":case "=":return{imgname:"equal",hscale:1,kind:"img-char"};case "\u30fc":return{imgname:"onbiki",hscale:1,kind:"img-char"};case "-":case "\u2015":case "\uff0d":case "\u2500":return{data:"\uff5c",kind:"cnv-char"};case "\u2191":return{data:"\u2192",kind:"cnv-char"};case "\u2192":case "\u21d2":return{data:"\u2193",kind:"cnv-char"};case "\u2193":return{data:"\u2190",
kind:"cnv-char"};case "\u2190":return{data:"\u2191",kind:"cnv-char"};default:return null}}},v={h1:{scale:3,family:"Meiryo",weight:"bold"},h2:{scale:2,family:"Meiryo",weight:"bold"},h3:{scale:1.5,family:"Meiryo"},h4:{scale:1.2,family:"Meiryo"},h5:{scale:1,family:"Meiryo",weight:"bold"}};l.prototype.lookChar=function(){if(this.pos==this.length)return"\n";if(this.pos>this.length)throw"BufferEnd";if(this.pos>=this.text.length)throw"BufferShort";return this.text.charAt(this.pos)};l.prototype.readUntil=
function(a){var b=this.pos,a=this.text.indexOf(a,b+1);if(a<0)throw"BufferShort";this.pos=a+1;return this.text.substring(b,a+1)};l.prototype.readMatch=function(a){var b=this.pos,a=this.text.substring(b).match(a).toString();if(a!="")this.pos=b+a.length;return this.text.substring(b,b+a.length)};l.prototype.stepSeekPos=function(){this.pos++};l.prototype.getSeekPos=function(){return this.pos};l.prototype.setSeekPos=function(a){if(a<this.length)this.pos=a};l.prototype.setText=function(a){this.text=a;this.length=
a.length;this.eof=true};l.prototype.getText=function(){return this.text};l.prototype.addText=function(a){this.text+=a;this.eof=this.text.length>=this.length};l.prototype.getSeekPercent=function(){return Math.floor(100*this.pos/this.length)};l.prototype.setEOF=function(a){return this.eof=a};l.prototype.isEOF=function(){return this.eof};n.prototype.getStream=function(){return this.stream};n.prototype.tag=function(a,b){var c=b.replace("<","").replace("/>","").replace(">","").split(/[\s\t\u3000]+/),d=
{};d.src=b;d.name=c[0].toLowerCase();d.attr={};for(var j=0;j<c.length;j++)if(c[j].match(/([^=]+)=(.+)/)){var f=RegExp.$1,e=g.cutQuote(RegExp.$2);d.attr[f]=e}return{type:"tag",data:d,pos:a}};n.prototype.character=function(a,b){var c=w.get(b);if(c){c.type="char";c.half=false;c.pos=a;if(c.kind=="img-char")c.data=b;else if(c.kind=="cnv-char")c.fromdata=b;return c}return b.match(/[\u3041\u30a1\u3043\u30a3\u3045\u30a5\u3047\u30a7\u3049\u30a9\u30f5\u30f6\u3063\u30c3\u3083\u30e3\u3085\u30e5\u3087\u30e7\u308e\u30ee]/)?
{type:"char",half:false,kind:"small-kana",data:b,pos:a}:b.charAt(0)=="&"?{type:"char",half:true,kind:"special-char",data:b,pos:a}:escape(b).charAt(1)=="u"?{type:"char",half:false,kind:"zen",data:b,pos:a}:{type:"char",half:true,kind:"small",data:b,pos:a}};n.prototype.word=function(a,b){return{type:"word",data:b,pos:a}};n.prototype.tcy=function(a,b){return{type:"tcy",data:b,pos:a}};n.prototype.getNext=function(){var a=this.stream.getSeekPos(),b=this.stream.lookChar();return b=="<"?this.tag(a,this.stream.readUntil(">")):
b=="&"?this.character(a,this.stream.readUntil(";")):p.canTransform&&b.match(/[0-9a-zA-Z!\.\?\/\_:#]/)?(b=this.stream.readMatch(/[0-9a-zA-Z!\.\?\/\_:#]+/),b.length<=2&&!isNaN(b)||b=="!?"||b=="!!"||b=="??"?this.tcy(a,b):this.word(a,b)):(this.stream.stepSeekPos(),this.character(a,b))};n.prototype.lookNextStr=function(){for(var a=this.stream.getSeekPos(),b=null;;){var c=this.getNext();if(c.type=="char"||c.type=="tcy"||c.type=="word"){b=c;break}}this.stream.setSeekPos(a);return b};n.prototype.skipUntilTag=
function(a){for(;;){var b=this.getNext();if(b.type=="tag"&&b.data.name==a)break}};n.prototype.skipCRLF=function(a){for(var b=0;;){var c=this.getNext();if(c.type!="char"||c.type=="char"&&c.data!="\r"&&c.data!="\n"){this.stream.setSeekPos(c.pos);break}c.data=="\n"&&b++;if(a&&b>=a)break}};o.prototype.init=function(){this.direction=this.direction.toLowerCase();this.isV=this.direction.match(/vertical/i)?true:false;this.baseNextLineSize=Math.floor(this.nextLineOffsetRate*this.fontSize);this.baseRubyFontSize=
this.fontSizeHalf=Math.floor(this.fontSize/2);this.baseExtraLineSize=this.baseNextLineSize-this.fontSize;this.isV?(this.invDirection="horizontal",this.extraFontSize=this.fontSizeHalf,this.width=Math.max(this.baseNextLineSize,this.width),this.height=Math.max(this.fontSize+this.extraFontSize,this.height),this.lineEndSize=this.height-this.extraFontSize,this.nextCharMaxSize=this.height,this.nextLineMaxSize=this.width):(this.invDirection="vertical",this.extraFontSize=this.fontSize,this.width=Math.max(this.fontSize+
this.extraFontSize,this.width),this.height=Math.max(this.baseNextLineSize,this.height),this.nextCharMaxSize=this.width-this.extraFontSize,this.nextLineMaxSize=this.height);this.linkColor=u.get(this.linkColor)};o.prototype.getIndentCount=function(a){return a.before+a.after};o.prototype.getIndentSize=function(a){return this.fontSize*a};o.prototype.getNextCharMaxSize=function(a){return this.nextCharMaxSize-this.getIndentSize(this.getIndentCount(a.curIndent))};o.prototype.getAlignSpaceSize=function(a,
b){return{width:this.isV?a+this.baseExtraLineSize:this.width-a-this.baseExtraLineSize,height:this.isV?this.height-b-this.baseExtraLineSize:b+this.baseExtraLineSize}};o.prototype.isAlignEnable=function(a,b){return this.isV?b*2>this.height:a*2>this.width};q.prototype.setActiveTag=function(a){this.activeTags[a.replace("/","")]=a.substring(0,1)!="/"};q.prototype.isActiveTag=function(a){return this.activeTags[a]||false};q.prototype.setFontScale=function(a,b){this.curFontScale=b;this.curFontSize=Math.floor(a.fontSize*
b);this.curFontSizeHalf=Math.floor(this.curFontSize/2)};q.prototype.inheritLine=function(){this.lineTokens=this.nextLineTokens;this.nextLineTokens=[];this.rubyTokens=this.nextRubyTokens;this.nextRubyTokens=[]};e.prototype.hasNextPage=function(){return this.parseEnd==false};e.prototype.getLexer=function(){return this.lexer};e.prototype.getTocTable=function(){return this.tocTable};e.prototype.isHeadNg=function(a){return a.match(/[\uff09\)\u300d\u3011\u3015\uff3d\]\u3002\u300f\uff1e\u3009\u300b\u3001\uff0e\.,]/)?
true:false};e.prototype.isHeadNgToken=function(a){return a.type!="char"?false:this.isHeadNg(a.data)};e.prototype.isTailNg=function(a){return a.match(/[\uff08\(\u300c\u3010\uff3b\u3014\u300e\uff1c\u3008\u300a]/)?true:false};e.prototype.isTailNgToken=function(a){return a.type!="char"?false:this.isTailNg(a.data)};e.prototype.isTextToken=function(a){return a.type=="char"||a.type=="word"||a.type=="tcy"};e.prototype.isTailConnectiveChar=function(a){return a.type=="char"&&a.data.match(/[\u3001\u3002\.\uff0e,\uff0c\u300d\u300f\uff09]/)};
e.prototype.isKakkoStartChar=function(a){return a.match(/[\u300c\u300e\u3010\uff3b\uff08\u300a\u3008\u226a\uff1c\[\(]/)?true:false};e.prototype.isKakkoEndChar=function(a){return a.match(/[\u300d\u300f\u3011\uff3d\uff09\u300b\u3009\u226b\uff1e\]\)]/)?true:false};e.prototype.isParserEnd=function(){return this.parseEnd};e.prototype.isNextCharOver=function(a,b,c){return b.seekNextChar+c.nextOffset>a.getNextCharMaxSize(b)};e.prototype.isNextLineOver=function(a,b,c){return b.seekNextLine+c>a.nextLineMaxSize};
e.prototype.isLineOverflow=function(a,b){return b.seekNextChar>a.getNextCharMaxSize(b)};e.prototype.setFont=function(a,b,c){c.scale&&this.setFontScale(a,b,parseFloat(c.scale));if(c["border-width"])b.curBorderSize=parseInt(c["border-width"]);if(c.color)b.curFontColor=u.get(c.color)};e.prototype.setFontScale=function(a,b,c){b.setFontScale(a,c)};e.prototype.resetFont=function(a,b){b.curFontScale=1;b.curFontColor=a.fontColor;b.curFontSize=a.fontSize;b.curFontSizeHalf=a.baseRubyFontSize;b.curBorderSize=
0};e.prototype.popFont=function(a,b){b.tagStack.pop();b.fontStack.pop();var c=b.fontStack.length;c>0?this.setFont(a,b,b.fontStack[c-1]):this.resetFont(a,b)};e.prototype.popIndent=function(a,b){var c=b.indentStack.pop();c&&(b.curIndent.before-=c.before,b.curIndent.after-=c.after)};e.prototype.getFontCss=function(a,b,c){b={};for(prop in c)if(prop=="scale"){var d=parseFloat(c.scale);b["font-size"]=Math.floor(a.fontSize*d)+"px";a.isV&&(b["line-height"]=Math.floor(a.fontSize*d)+"px")}else prop=="family"?
b["font-family"]=c[prop]:prop=="weight"?b["font-weight"]=c[prop]:prop=="color"?b.color=c[prop]:prop=="bgcolor"?b["background-color"]=c[prop]:prop=="border-radius-tl"?g.setRadius("top","left",parseInt(c[prop]),b):prop=="border-radius-tr"?g.setRadius("top","right",parseInt(c[prop]),b):prop=="border-radius-bl"?g.setRadius("bottom","left",parseInt(c[prop]),b):prop=="border-radius-br"?g.setRadius("bottom","right",parseInt(c[prop]),b):prop=="border-radius"?(d=parseInt(c[prop]),g.setRadius("top","left",
d,b),g.setRadius("top","right",d,b),g.setRadius("bottom","left",d,b),g.setRadius("bottom","right",d,b)):prop=="border-width"?b["border-width"]=parseInt(c[prop])+"px":prop=="border-color"?b["border-color"]=c[prop]:prop=="border-style"&&(b["border-style"]=c[prop]);return b};e.prototype.tagFontStart=function(a,b,c){return g.tagStart(a.isV?"div":"span",{style:g.inlineCss(this.getFontCss(a,b,c))},false)};e.prototype.tagFontEnd=function(a){return a.isV?"</div>":"</span>"};e.prototype.getMaxFontScale=function(a){for(var b=
1,c=0;c<a.length;c++){var d=a[c];if(d.type=="tag"&&(d=d.data,d.name=="font"&&d.attr.scale&&(d=parseFloat(d.attr.scale),d>b)))for(var j=c+1;j<a.length;j++)this.isTextToken(a[j])&&(b=d)}return b};e.prototype.getLineTextLength=function(a){for(var b=0,c=0;c<a.length;c++){var d=a[c];this.isTextToken(d)&&(b+=d.nextOffset)}return b};e.prototype.getTokenLength=function(a){return a.type=="tag"?a.data.src.length:a.data.length};e.prototype.getLineTailStr=function(a){for(var b=a.lineTokens.length-1;b>=0;b--){var c=
a.lineTokens[b];if(this.isTextToken(c))return c}return null};e.prototype.getRubyToken=function(a,b,c,d){return{pos:c,yomi:d,fontSize:b.curFontSizeHalf,nextOffset:b.curFontSizeHalf,requireSpaceSize:b.curFontSize}};e.prototype.getRubyCss=function(a,b,c,d,j){var b={position:"absolute","font-size":d+"px"},f=j>1?Math.floor((j-1)*a.baseExtraLineSize/2):0;a.isV?(b["margin-top"]=c+"px",b["line-height"]=p.isMobileSafari?"0.9em":"1.1em",j>1&&d<=a.baseRubyFontSize&&(b["margin-left"]="-"+f+"px",b["float"]="left")):
(b["margin-left"]=c+"px",j>1&&d<=a.baseRubyFontSize&&(b["padding-top"]=f+f+f+"px"));return b};e.prototype.getDotToken=function(a,b,c,d){var j=a.nextLineOffsetRate-1,a=Math.floor(b.curFontSize*j),j=Math.floor(b.curFontSize*(1-j)/2);return{pos:c+j,count:d,fontSize:a,nextOffset:b.curFontSize,requireSpaceSize:b.curFontSize,offsetHead:j,hspace:b.curFontSize-a}};e.prototype.getDotCss=function(a,b,c){return a.isV?{position:"absolute","margin-top":c.pos,"font-size":c.fontSize+"px","line-height":c.nextOffset+
"px","font-weight":"bold"}:{position:"absolute","margin-left":c.pos,"font-size":c.fontSize,"letter-spacing":c.hspace+"px","font-weight":"bold"}};e.prototype.getTailCharToken=function(a){for(var b=a.length-1;b>=0;b--)if(this.isTextToken(a[b]))return a[b];return null};e.prototype.isTailNgLine=function(a){return(a=this.getTailCharToken(a))&&a.type=="char"?this.isTailNgToken(a):false};e.prototype.sweepOverflowTokens=function(a,b){for(var c=b.lineTokens.length,d=a.getNextCharMaxSize(b),j=0,f=0;f<c;f++){var e=
b.lineTokens[f];if(this.isTextToken(e)&&(j+=e.nextOffset,j>d))break}if(0<f&&f<c)b.nextLineTokens=b.lineTokens.slice(f).concat(b.nextLineTokens),b.lineTokens=b.lineTokens.slice(0,f)};e.prototype.sweepWhileMatch=function(a,b,c,d,j){for(var f=false;a.length>0;){var e=a.pop();if(c(e))b.push(e),f=true;else if(j(e)){b.push(e);f=true;break}else if(d(e)){a.push(e);break}}return f};e.prototype.fixLineEnd=function(a,b,c){var d=this;(a=this.getTailCharToken(b))&&this.isTailNgToken(a)&&this.sweepWhileMatch(b,
c,function(a){return d.isTailNgToken(a)},function(a){return!d.isTailNgToken(a)},function(){return false})&&c.sort(function(a,b){return a.pos-b.pos});this.isHeadNgToken(c[0])&&this.sweepWhileMatch(b,c,function(){return false},function(){return false},function(a){return!d.isHeadNgToken(a)})&&c.sort(function(a,b){return a.pos-b.pos})};e.prototype.parseTag=function(a,b,c,d,j){var e=d.data;c.setActiveTag(e.name);if(this.elementHandler[e.name])this.elementHandler[e.name](this,a,b,c,d);else e.name=="a"?
this.parseStraightForwardTagStart(a,b,c,d):e.name=="/a"?this.parseStraightForwardTagEnd(a,b,c,d):e.name=="b"||e.name=="strong"?this.parseStraightForwardTagStart(a,b,c,d):e.name=="/b"||e.name=="/strong"?this.parseStraightForwardTagEnd(a,b,c,d):e.name=="ruby"?this.parseRuby(a,b,c,d):e.name=="rt"?a.skipUntilTag("/rt"):e.name=="rp"?a.skipUntilTag("/rp"):e.name=="font"?this.parseFontStart(a,b,c,d):e.name=="/font"?this.parseFontEnd(a,b,c,d):e.name=="img"?this.parseImg(a,b,c,d):e.name=="end-page"?this.parseEndPage(a,
b,c,d,j):e.name=="dot"?this.parseDot(a,b,c,d):e.name=="indent"?this.parseIndentStart(a,b,c,d):e.name=="/indent"?this.parseIndentEnd(a,b,c,d):e.name=="toc"?this.parseToc(a,b,c,d):e.name=="pack"?this.parsePack(a,b,c,d):e.name=="h1"||e.name=="h2"||e.name=="h3"||e.name=="h4"||e.name=="h5"?this.parseHeaderStart(a,b,c,d):e.name=="/h1"||e.name=="/h2"||e.name=="/h3"||e.name=="/h4"||e.name=="/h5"?this.parseHeaderEnd(a,b,c,d):e.name=="blockquote"?this.parseBlockquoteStart(a,b,c,d):e.name=="/blockquote"?this.parseBlockquoteEnd(a,
b,c,d):e.name=="layout"?this.parseInlineLayoutStart(a,b,c,d):e.name=="/layout"&&this.parseInlineLayoutEnd(a,b,c,d)};e.prototype.parseInlineLayoutStart=function(a,b,c,d){this.getLineTextLength(c.lineTokens)>0&&(a.skipCRLF(),this.pushLine(a,b,c,false));this.setMetricsLayout(a,b,c,d);this.pushInlineLayout(a,b,c,d)};e.prototype.parseInlineLayoutEnd=function(a,b,c,d){a.skipCRLF();this.pushLine(a,b,c,d,false);throw"PageEnd";};e.prototype.parseStraightForwardTagStart=function(a,b,c,d){c.lineTokens.push(d);
c.tagStack.push(d)};e.prototype.parseStraightForwardTagEnd=function(a,b,c,d){c.lineTokens.push(d);c.tagStack.pop()};e.prototype.parseIndentStart=function(a,b,c,d){d=d.data.attr;a=d.before?parseInt(d.before):0;b=d.after?parseInt(d.after):0;d=d.count?parseInt(d.count):0;d>0&&(a=b=d);if(a>0||b>0)c.indentStack.push({before:a,after:b}),c.curIndent.before+=a,c.curIndent.after+=b};e.prototype.parseIndentEnd=function(a,b,c){a.skipCRLF();try{this.pushLine(a,b,c,false)}finally{this.popIndent(b,c)}};e.prototype.parseFontStart=
function(a,b,c,d){c.lineTokens.push(d);c.tagStack.push(d);c.fontStack.push(d.data.attr);this.setFont(b,c,d.data.attr)};e.prototype.parseFontEnd=function(a,b,c,d){c.lineTokens.push(d);this.popFont(b,c)};e.prototype.parseEndPage=function(a,b,c,d,e){e?a.getStream().setSeekPos(d.pos):(a.skipCRLF(),this.pushLine(a,b,c,d,false));throw"PageEnd";};e.prototype.parseHeaderStart=function(a,b,c,d){this.parseFontStart(a,b,c,{type:"tag",data:{name:"font",attr:v[d.data.name]},pos:-1})};e.prototype.parseHeaderEnd=
function(a,b,c,d){d=v[d.data.name.replace("/","")].scale;d=Math.floor(b.baseExtraLineSize*d);this.parseFontEnd(a,b,c,{type:"tag",data:{name:"/font",attr:{}},pos:-1});this.pushLine(a,b,c,false);a.skipCRLF();this.pushSpaceLine(a,b,c,d)};e.prototype.parseBlockquoteStart=function(a,b,c){a.skipCRLF();this.parseIndentStart(a,b,c,{type:"tag",data:{name:"indent",attr:{count:2}},pos:-1});this.parseFontStart(a,b,c,{type:"tag",data:{name:"font",attr:{scale:0.8}},pos:-1})};e.prototype.parseBlockquoteEnd=function(a,
b,c){this.parseIndentEnd(a,b,c,{type:"tag",data:{name:"/indent"},pos:-1});this.parseFontEnd(a,b,c,{type:"tag",data:{name:"/font"},pos:-1});a.skipCRLF();this.pushLine(a,b,c,false)};e.prototype.parseRuby=function(a,b,c,d){for(var e="",f="ruby",g=c.seekNextChar,h=0,d=d.pos+this.getTokenLength(d),i=b.getNextCharMaxSize(c);;){var m=a.getNext();if(m.type=="tag")if(f=m.data.name,f=="/ruby"){a.getStream().setSeekPos(d);break}else f=="rb"?d=m.pos+this.getTokenLength(m):f=="/rt"&&(g+c.curFontSize>=i?(g=0,c.nextRubyTokens.push(this.getRubyToken(b,
c,g,e))):(c.rubyTokens.push(this.getRubyToken(b,c,g,e)),g+=h),e="");else this.isTextToken(m)&&m.kind!="img-char"&&(f=="rt"?e+=m.data:f!="rp"&&(this.setMetricsStr(a,b,c,m),h+=m.nextOffset))}};e.prototype.parseDot=function(a,b,c,d){for(var e=c.seekNextChar,f=-1,g=0;;)if(d=a.getNext(),d.type=="tag"&&d.data.name=="/dot"&&g>0){c.dotTokens.push(this.getDotToken(b,c,e,g));f>=0&&a.getStream().setSeekPos(f);break}else if(d.type=="char"){if(f<0)f=d.pos;g++}};e.prototype.parseToc=function(a,b,c){for(var b="",
d=a.getStream().getSeekPos();;){var e=a.getNext();if(e.type=="tag"&&e.data.name=="/toc"){this.tocTable.push({title:b,pageNo:c.curPageNo});a.getStream().setSeekPos(d);break}else this.isTextToken(e)&&(b+=e.data)}};e.prototype.parsePack=function(a,b,c,d){var e="";for(a.getStream().getSeekPos();;){var f=a.getNext();if(f.type=="tag"&&f.data.name=="/pack"){e!=""&&this.parseTcy(a,b,c,a.tcy(d.pos,e));break}else this.isTextToken(f)&&(e+=f.data)}};e.prototype.parseChar=function(a,b,c,d){d.data!="\r"&&(d.data==
"\n"?this.pushLine(a,b,c,false):(this.setMetricsChar(a,b,c,d),this.pushChar(a,b,c,d)))};e.prototype.parseWord=function(a,b,c,d){this.setMetricsWord(a,b,c,d);this.pushWord(a,b,c,d)};e.prototype.parseTcy=function(a,b,c,d){b.isV?(this.setMetricsTcy(a,b,c,d),this.pushTcy(a,b,c,d)):(d.type="word",this.parseWord(a,b,c,d))};e.prototype.parseImg=function(a,b,c,d){this.getLineTextLength(this.context.lineTokens)>0&&this.pushLine(a,b,c,false);this.setMetricsImg(a,b,c,d);this.pushImg(a,b,c,d)};e.prototype.setMetricsStr=
function(a,b,c,d){d.type=="char"?this.setMetricsChar(a,b,c,d):d.type=="word"?this.setMetricsWord(a,b,c,d):d.type=="tcy"&&this.setMetricsTcy(a,b,c,d)};e.prototype.setMetricsChar=function(a,b,c,d){d.kind=="small-kana"?this.setMetricsSmallKana(a,b,c,d):d.kind=="img-char"?this.setMetricsImgChar(a,b,c,d):d.half?this.setMetricsHalfChar(a,b,c,d):this.setMetricsFullChar(a,b,c,d)};e.prototype.setMetricsSmallKana=function(a,b,c,d){d.nextOffset=c.curFontSize;d.fontSize=c.curFontSize};e.prototype.setMetricsImgChar=
function(a,b,c,d){var e=d.data,f=d.imgname;d.height=d.nextOffset=d.hscale==1?c.curFontSize:d.hscale==0.5?c.curFontSizeHalf:Math.floor(c.curFontSize*d.hscale);d.fontSize=c.curFontSize;d.color=c.isActiveTag("a")?b.linkColor:c.curFontColor;if(this.isKakkoStartChar(e)){if((a=this.getLineTailStr(c))&&!this.isKakkoStartChar(a.data))d.nextOffset+=c.curFontSizeHalf,d.marginTop=c.curFontSizeHalf}else if(this.isKakkoEndChar(e)){if(b=a.lookNextStr())if(a=b.data,b=b.imgname,!this.isKakkoEndChar(a)&&b!="tenten"&&
b!="kuten"&&b!="touten"&&a!="\u30fb")d.nextOffset=c.curFontSize}else if(f=="kuten"||f=="touten")if(b=a.lookNextStr())if(a=b.data,!this.isKakkoEndChar(a))d.nextOffset=c.curFontSize};e.prototype.setMetricsHalfChar=function(a,b,c,d){d.nextOffset=p.canTransform||!b.isV?c.curFontSizeHalf:c.curFontSize;d.fontSize=c.curFontSize};e.prototype.setMetricsFullChar=function(a,b,c,d){d.nextOffset=c.curFontSize;d.fontSize=c.curFontSize};e.prototype.setMetricsTcy=function(a,b,c,d){d.fontSize=c.curFontSize;d.nextOffset=
c.curFontSize};e.prototype.setMetricsWord=function(a,b,c,d){d.fontSize=c.curFontSize;d.fontWidth=c.curFontSizeHalf;d.nextOffset=d.data.length*c.curFontSizeHalf};e.prototype.setMetricsImg=function(a,b,c,d){c=d.data.attr;a=parseInt(c.width);c=parseInt(c.height);if(a>b.width)var e=b.width-b.fontSize,f=Math.floor(c*(e/a)),a=e,c=f;c>b.height&&(f=b.height-b.fontSize,a=e=Math.floor(a*(f/c)),c=f);d.width=a;d.height=c;d.nextOffset=(b.isV?a:c)+b.baseExtraLineSize};e.prototype.setMetricsLayout=function(a,b,
c,d){a=d.data.attr;d.width=parseInt(a.width);d.height=parseInt(a.height);d.nextOffset=b.isV?d.width:d.height};e.prototype.pushLine=function(a,b,c,d){var e=this.getMaxFontScale(c.lineTokens),f=c.curBorderSize+c.curBorderSize,g=Math.floor(b.baseNextLineSize*e);g+=f;if(this.isNextLineOver(b,c,g))throw d||c.repushTokenStack.push({type:"char",half:true,kind:"small",data:"\n",pos:-1}),"PageEnd";var d=Math.floor(b.fontSize*e)+f,f=g-d,h=this.makeMainText(b,c,e),i=this.makeRubyText(a,b,c,e),e=this.makeDotText(b,
c,e);c.pageHtml+=this.makeExtraLine(b,c,i+e,f);c.pageHtml+=this.makeTextLine(b,c,h,d);c.pageHeadPos=a.getStream().getSeekPos();c.seekNextLine+=g;c.seekNextChar=this.getLineTextLength(c.nextLineTokens);c.inheritLine()};e.prototype.pushSpaceLine=function(a,b,c,d){if(!this.isNextLineOver(b,c,d)&&c.seekNextLine!=0&&c.seekNextChar==0)c.pageHtml+=this.makeTextLine(b,c,"&nbsp;",d),c.seekNextLine+=d,c.pageHeadPos=a.getStream().getSeekPos()};e.prototype.pushChar=function(a,b,c,d){c.curCharCount++;this.isNextCharOver(b,
c,d)?(this.isLineOverflow(b,c)&&this.sweepOverflowTokens(b,c),this.isTailConnectiveChar(d)&&c.nextLineTokens.length==0?(d.fontSize=b.fontSize,d.height=b.fontSizeHalf,c.lineTokens.push(d),a.skipCRLF(1)):(c.nextLineTokens.push(d),this.fixLineEnd(b,c.lineTokens,c.nextLineTokens)),this.pushLine(a,b,c,true)):(c.lineTokens.push(d),c.seekNextChar+=d.nextOffset)};e.prototype.pushWord=function(a,b,c,d){c.curCharCount+=d.data.length;var e=b.getNextCharMaxSize(c),f=e-c.seekNextChar;f<d.nextOffset?d.nextOffset>
e&&f>d.fontWidth?(d.data=d.data.substring(0,Math.floor(f/d.fontWidth)),d.nextOffset=f,c.lineTokens.push(d),this.pushLine(a,b,c,true),a.getStream().setSeekPos(d.pos+d.data.length)):(c.nextLineTokens.push(d),this.pushLine(a,b,c,true)):(c.lineTokens.push(d),c.seekNextChar+=d.nextOffset)};e.prototype.pushTcy=function(a,b,c,d){c.curCharCount++;b.height-c.seekNextChar<d.nextOffset?(c.nextLineTokens.push(d),this.pushLine(a,b,c,true)):(c.lineTokens.push(d),c.seekNextChar+=d.nextOffset)};e.prototype.pushImg=
function(a,b,c,d){if(b.nextLineMaxSize-c.seekNextLine<d.nextOffset)throw a.getStream().setSeekPos(d.pos),"PageEnd";a.skipCRLF();c.seekNextLine+=d.nextOffset;c.pageHtml+=this.makeImgText(a,b,c,d);c.pageHeadPos=a.getStream().getSeekPos()};e.prototype.pushInlineLayout=function(a,b,c,d){if(!(d.width>b.width||d.height>b.height)){if(this.isNextLineOver(b,c,d.nextOffset))throw"PageEnd";c.seekNextLine+=d.nextOffset;c.pageHtml+=this.makeInlineLayoutText(a,b,c,d);c.pageHeadPos=a.getStream().getSeekPos()}};
e.prototype.makeTokenText=function(a,b,c,d){return c.type=="tag"?(c=c.data,c.name=="font"?this.tagFontStart(a,b,c.attr):c.name=="/font"?this.tagFontEnd(a):c.name=="indent"||c.name=="/indent"?"":g.tagStart(c.name,c.attr,false)):!a.isV?c.type=="char"&&c.kind=="cnv-char"?c.fromdata:c.data:c.type=="word"?this.makeWordText(a,b,c,d):c.type=="tcy"?this.makeTcyText(a,b,c):this.makeCharText(a,b,c)};e.prototype.makeCharText=function(a,b,c){return!a.isV?c.data:c.kind=="small-kana"?this.makeSmallKanaText(a,b,
c):c.kind=="img-char"?this.makeImgCharText(a,b,c):c.half?this.makeHalfCharText(a,b,c):this.makeFullCharText(a,b,c)};e.prototype.makeFullCharText=function(a,b,c){return c.data+"<br />"};e.prototype.makeImgCharText=function(a,b,c){a=g.tagStart("img",{src:g.filenameConcat(a.charImgRoot,c.imgname+"/"+c.color+".png"),width:c.fontSize,height:c.height,style:c.marginTop?"margin-top:"+c.marginTop+"px":""},true);return g.tagWrap("div",{"class":"img-char",style:g.inlineCss({clear:"both","line-height":c.nextOffset+
"px",height:c.nextOffset+"px"})},a)};e.prototype.makeSmallKanaText=function(a,b,c){return g.tagWrap("div",{style:g.inlineCss({overflow:"visible",position:"relative",top:p.isMobileSafari?"-0.22em":"-0.12em",right:"-0.12em",height:c.nextOffset+"px","line-height":c.nextOffset+"px"})},c.data)};e.prototype.makeHalfCharText=function(a,b,c){return g.tagWrap("div",{style:g.inlineCss({height:c.nextOffset+"px","line-height":c.nextOffset+"px"})},c.data)};e.prototype.makeWordText=function(a,b,c,d){b=c.data.length<=
2?0:c.nextOffset-c.fontSize;a=d>1?a.fontSize*d:a.fontSize;c.data.length>2&&d>1&&(b=c.nextOffset-a);return p.isIE?g.tagWrap("div",{style:g.inlineCss({"line-height":a+"px","writing-mode":"tb-rl"})},c.data):g.tagWrap("div",{style:g.inlineCss({width:a+"px",height:Math.floor(c.data.length*c.fontSize/2)+"px",overflow:"visible"})},g.tagWrap("div",{style:g.inlineCss({width:a+"px","line-height":a+"px","margin-bottom":b+"px","-webkit-transform":"rotate(90deg)","-webkit-transform-origin":"50% 50%","-moz-transform":"rotate(90deg)",
"-moz-transform-origin":"50% 50%","-o-transform":"rotate(90deg)","-o-transform-origin":"50% 50%"})},c.data))};e.prototype.makeTcyText=function(a,b,c){return c.data+"<br />"};e.prototype.makeImgAlignText=function(a,b,c,d,e){var f=d.data.attr.align,f=f=="top"||f=="left",i={src:d.data.attr.src,width:d.width,height:d.height},h=b.baseExtraLineSize+"px";b.isV?h=f?{margin:[0,h,h,0].join(" ")}:{margin:[h,h,0,0].join(" ")}:(h=f?{margin:[h,h,0,0].join(" ")}:{margin:[h,0,0,h].join(" ")},h["float"]="left");i.style=
g.inlineCss(h);h="";h+=this.makeLineTokensText(b,c,1);h+=g.tagStart("img",i,true);h+=this.makeTagStackCloseText(b,c);c.inheritLine();a=this.makeInlinePageText(a,b,c,e.width,e.height);b.isV||(a=g.tagWrap("div",{style:"float:left"},a));return g.tagWrap("div",{style:g.inlineCss(b.isV?{"float":"right"}:{width:b.width+"px",height:d.nextOffset+"px"})},f?h+a:a+h)};e.prototype.makeImgLineText=function(a,b,c,d){a="";d=g.tagStart("img",{src:d.data.attr.src,width:d.width,height:d.height,style:g.inlineCss(b.isV?
{"margin-right":b.baseExtraLineSize+"px","float":"right"}:{"margin-bottom":b.baseExtraLineSize+"px"})},true);a+=this.makeLineTokensText(b,c,1);a+=d;a+=this.makeTagStackCloseText(b,c);c.inheritLine();return a};e.prototype.makeImgText=function(a,b,c,d){if(d.data.attr.align){var e=b.getAlignSpaceSize(d.width,d.height);return b.isAlignEnable(e.width,e.height)?this.makeImgAlignText(a,b,c,d,e):this.makeImgLineText(a,b,c,d)}else return this.makeImgLineText(a,b,c,d)};e.prototype.makeInlineLayoutText=function(a,
b,c,d){var e=d.data.attr,f=b.direction;b.direction=e.direction||b.invDirection;b.init();var i=this.makeInlinePageText(a,b,c,d.width,d.height);c.lineTokens=[];c.nextLineTokens=[];b.direction=f;b.init();return e.align?(e=e.align=="top"||e.align=="left",a=this.makeInlinePageText(a,b,c,b.isV?d.width:b.width-d.width,b.isV?b.height-d.height:d.height),b.isV?g.tagWrap("div",{style:"float:right"},e?i+a:a+i):(b=g.tagWrap("div",{style:"float:left"},i),i=g.tagWrap("div",{style:"float:left"},a),g.tagWrap("div",
{},e?b+i:i+b)+"<div style='clear:both; line-height:0;'></div>")):tagWrap("div",{style:"float:"+(b.isV?"right":"left")},i)};e.prototype.makeTextLine=function(a,b,c,d){return a.isV?g.tagWrap("div",{"class":"nehan-vertical-text-line",style:g.inlineCss({"float":"right","text-align":"center","line-height":p.isMobileSafari?"0.9em":a.fontSize+"px",width:d+"px",height:a.height+"px"})},c):g.tagWrap("div",{"class":"nehan-horizontal-text-line",style:g.inlineCss({width:a.width+"px",height:d+"px","text-align":"left",
"line-height":d+"px"})},c)};e.prototype.makeExtraLine=function(a,b,c,d){return a.isV?g.tagWrap("div",{"class":"nehan-vertical-extra-line",style:g.inlineCss({"float":"right","text-align":"left",width:d+"px",height:a.height+"px","line-height":p.isMobileSafari?"0.9em":"1em"})},c==""?"&nbsp;":c):g.tagWrap("div",{"class":"nehan-horizontal-extra-line",style:g.inlineCss({width:a.width+"px",height:d+"px","line-height":d+"px"})},c)};e.prototype.makeLineTokensText=function(a,b,c){for(var d="",e=0;e<b.lineTokens.length;e++)d+=
this.makeTokenText(a,b,b.lineTokens[e],c);return d};e.prototype.makeMainText=function(a,b,c){c=this.makeLineTokensText(a,b,c);c=this.makeIndentStackWrapText(a,b,c);c+=this.makeTagStackCloseText(a,b,c);return c};e.prototype.makeIndentStackWrapText=function(a,b,c){for(var d="",e=0;e<b.curIndent.before;e++)d+=this.makeTokenText(a,b,{type:"char",half:false,kind:"zen",data:"\u3000"},1);d+=c;for(e=0;e<b.curIndent.after;e++)d+=this.makeTokenText(a,b,{type:"char",half:false,kind:"zen",data:"\u3000"},1);return d};
e.prototype.makeTagStackCloseText=function(a,b){for(var c="",d=b.tagStack.length-1;d>=0;d--){var e=b.tagStack[d];c+=this.makeTagCloseText(a,e);b.nextLineTokens.unshift(e)}return c};e.prototype.makeTagCloseText=function(a,b){return b.data.name=="font"?this.tagFontEnd(a):"</"+b.data.name+">"};e.prototype.makeDotText=function(a,b,c){for(var d="",e=[],f=a.getNextCharMaxSize(b),i=0;i<b.dotTokens.length;i++){for(var h=b.dotTokens[i],k=h.pos,m="";h.count>0;){if(f-k<h.requireSpaceSize){k=g.deepCopy(h);k.pos=
h.offsetHead;e.push(k);break}m+=this.makeCharText(a,b,{type:"char",half:false,kind:"zen",data:"\u30fb",fontSize:h.fontSize});k+=h.nextOffset;h.count--}m!=""&&(h=this.getDotCss(a,b,h,c),d+=g.tagWrap("span",{style:g.inlineCss(h)},m))}b.dotTokens=e;return d};e.prototype.makeRubyText=function(a,b,c,d){var a="",e=b.getIndentSize(c.curIndent.before);b.getIndentSize(c.curIndent.after);for(var f=b.getNextCharMaxSize(c)+e,i=0;i<c.rubyTokens.length;i++){for(var h=c.rubyTokens[i],k=h.pos+e,m="",l=0;l<h.yomi.length;l++){c1=
h.yomi.charAt(l);if(f-k<h.requireSpaceSize){k=g.deepCopy(h);k.pos=0;k.yomi=h.yomi.substring(l);c.nextRubyTokens.push(k);break}m+=this.makeCharText(b,c,{type:"char",half:false,kind:"zen",data:c1,fontSize:h.fontSize});k+=h.nextOffset}m!=""&&(h=this.getRubyCss(b,c,h.pos+e,h.fontSize,d),a+=g.tagWrap("span",{style:g.inlineCss(h)},m))}return a};e.prototype.makeInlinePageText=function(a,b,c,d,e){var a=b.width,f=b.height,g=c.seekNextLine,h=c.pageHtml;b.width=d;b.height=e;b.init();c.seekNextLine=0;c.seekNextChar=
0;c.pageHtml="";d=this.outputPage(true);if(c.nextLineTokens.length>0){for(e=0;e<c.nextLineTokens.length;e++){var i=c.nextLineTokens[e];c.lineTokens.push(i);c.seekNextChar+=i.nextOffset}c.nextLineTokens=[]}b.width=a;b.height=f;b.init();c.seekNextLine=g;c.pageHtml=h;return d};e.prototype.makePageText=function(a,b,c,d){a=g.tagWrap("div",{"class":d?"nehan-page nehan-page-inline":"nehan-page",style:g.inlineCss({width:b.width+"px",height:b.height+"px","font-size":b.fontSize+"px","white-space":"nowrap"})},
c.pageHtml);c.pageHtml="";c.seekNextLine=0;d||c.curPageNo++;return a};e.prototype.setElementHandler=function(a,b){this.elementHandler[a]=b};e.prototype.getNextToken=function(a,b){return b.repushTokenStack.length>0?b.repushTokenStack.pop():a.getNext()};e.prototype.reset=function(a){this.lexer.getStream().setSeekPos(0);this.layout=a;this.context=new q(a);this.tocTable=[];this.parseEnd=false};e.prototype.outputPage=function(a){for(;;)try{var b=this.getNextToken(this.lexer,this.context);b.type=="char"?
this.parseChar(this.lexer,this.layout,this.context,b):b.type=="word"?this.parseWord(this.lexer,this.layout,this.context,b):b.type=="tcy"?this.parseTcy(this.lexer,this.layout,this.context,b):b.type=="tag"&&this.parseTag(this.lexer,this.layout,this.context,b,a)}catch(c){if(c=="BufferEnd"){this.parseEnd=true;if(this.context.lineTokens.length>0)try{this.pushLine(this.lexer,this.layout,this.context,false)}catch(d){if(d=="PageEnd")this.parseEnd=false}return this.makePageText(this.lexer,this.layout,this.context,
a)}else if(c=="PageEnd")return this.makePageText(this.lexer,this.layout,this.context,a);else throw c;}};k.prototype.getContext=function(){return this.parser.context};k.prototype.getLayout=function(){return this.layout};k.prototype.createTagToken=function(a,b){return{type:"tag",data:{name:a,attr:b},pos:-1}};k.prototype.skipCRLF=function(){this.lexer.skipCRLF()};k.prototype.pushLine=function(){this.parser.pushLine(this.lexer,this.layout,this.parser.context,false)};k.prototype.pushSpaceLine=function(a){this.parser.pushSpaceLine(this.lexer,
this.layout,this.parser.context,a)};k.prototype.startFont=function(a){this.parser.parseFontStart(this.lexer,this.layout,this.parser.context,this.createTagToken("font",a))};k.prototype.endFont=function(){this.parser.parseFontEnd(this.lexer,this.layout,this.parser.context,this.createTagToken("/font",{}))};k.prototype.startIndent=function(a,b){this.parser.parseIndentStart(this.lexer,this.layout,this.parser.context,this.createTagToken("indent",{before:a,after:b}))};k.prototype.endIndent=function(){this.parser.parseIndentEnd(this.lexer,
this.layout,this.parser.context,this.createTagToken("/indent",{}))};k.prototype.pushImg=function(a){this.parser.parseImg(this.lexer,this.layout,this.parser.context,this.createTagToken("img",a))};k.prototype.pushChar=function(a){this.parser.parseChar(this.lexer,this.layout,this.parser.context,this.lexer.character(-1,a))};k.prototype.pushWord=function(a){this.parser.parseWord(this.lexer,this.layout,this.parser.context,this.lexer.word(-1,a))};k.prototype.pushTcy=function(a){this.parser.parseTcy(this.lexer,
this.layout,this.parser.context,this.lexer.tcy(-1,a))};i.prototype.reset=function(a){this.layout=new o(a);this.parser.reset(this.layout);this.cache=[]};i.prototype.hasNextPage=function(){return this.parser.hasNextPage()};i.prototype.isEnablePage=function(a){return a==0?true:this.cache[a]?true:this.cache.length==a&&this.parser.hasNextPage()?true:false};i.prototype.getLayout=function(){return this.layout};i.prototype.getText=function(){return this.lexer.getStream().getText()};i.prototype.setText=function(a){return this.lexer.getStream().setText(a)};
i.prototype.addText=function(a){return this.lexer.getStream().addText(a)};i.prototype.isEOF=function(){return this.lexer.getStream().isEOF()};i.prototype.getTocTable=function(){return this.parser.getTocTable()};i.prototype.getTocCount=function(){return this.parser.getTocTable().length};i.prototype.getPageCount=function(){return this.parser.context.curPageNo};i.prototype.setElementHandler=function(a,b){var c=this;this.parser.setElementHandler(a,function(a,e,f,g,h){b(c.parserProxy,h.data)})};i.prototype.setPageHeadPos=
function(a,b,c){this.pageHeadPos[a]={spos:b,cpos:c}};i.prototype.getPageHeadPos=function(a){return this.pageHeadPos[a]};i.prototype.setPageCache=function(a,b){this.cache[a]=b};i.prototype.getPageSourceText=function(a){if(a+1<this.getPageCount()){var b=this.getPageHeadPos(a).spos,a=this.getPageHeadPos(a+1).spos;return this.lexer.getStream().getText().substring(b,a)}return""};i.prototype.getPageNoFromSeekPos=function(a){for(var b=0;b<this.pageHeadPos.length-1;b++)if(this.pageHeadPos[b].spos<=a&&a<this.pageHeadPos[b+
1].spos)return b;return this.pageHeadPos[b].spos<=a&&a<=this.lexer.getStream().getText().length?b:-1};i.prototype.outputPage=function(a){if(this.cache[a])return this.cache[a];if(!this.resuming&&!this.lexer.getStream().isEOF())this.restoreContext=g.deepCopy(this.parser.context);var b=this.getPageHeadPos(a);try{var c=this.parser.outputPage(false),d=this.lexer.getStream().getSeekPercent(),e=this.lexer.getStream().isEOF()?this.parser.context.pageHeadPos:this.lexer.getStream().getSeekPos(),f=this.parser.context.curCharCount;
if(!this.parser.hasNextPage())this.pageCount=a+1;this.resuming=false;this.setPageHeadPos(a+1,e,f);this.cache[a]={html:c,percent:d,spos:b.spos,cpos:b.cpos};return this.cache[a]}catch(i){if(i=="BufferShort")this.resuming=true,this.parser.context=g.deepCopy(this.restoreContext),this.parser.lexer.getStream().setSeekPos(b.spos);throw i;}};s.prototype.init=function(a){for(var a=a.split(/[\s\t]/),b=0;b<a.length;b++){var c=a[b];if(c=="lp-vertical")this.direction="vertical";else if(c=="lp-horizontal")this.direction=
"horizontal";else if(c.match(/span-([0-9]+)/))this.width=parseInt(RegExp.$1)*40-10;else if(c.match(/lp-width-([0-9]+)/))this.width=parseInt(RegExp.$1);else if(c.match(/lp-height-([0-9]+)/))this.height=parseInt(RegExp.$1);else if(c.match(/lp-font-size-([0-9]+)/))this.fontSize=parseInt(RegExp.$1);else if(c.match(/lp-font-color-(.+)/))this.fontColor=RegExp.$1.toUpperCase();else if(c.match(/lp-link-color-(.+)/))this.linkColor=RegExp.$1.toUpperCase();else if(c.match(/lp-group-([a-zA-Z0-9\-_]+)/))this.groupName=
RegExp.$1;else if(c.match(/lp-order-([0-9]+)/))this.order=parseInt(RegExp.$1);else if(c=="lp-end")this.isEnd=true}a=this.node.style;a.width=this.width+"px";a.height=this.height+"px"};s.prototype.getLayout=function(){return new o({direction:this.direction,width:this.width,height:this.height,fontSize:this.fontSize,fontColor:this.fontColor,linkColor:this.linkColor})};s.prototype.getText=function(a){var b=this.node.innerHTML;return a?b.replace(/<br>/gi,"\n").replace(/<br \/>/gi,"\n"):b.replace(/<br>/gi,
"").replace(/<br \/>/gi,"")};r.prototype.init=function(){this.grids.sort(function(a,b){return a.order-b.order});this.provider=new i(this.grids[0].getLayout(),this.grids[0].getText(this.opt.convBR||true));this.rootNode=document.createElement("div");return this};r.prototype.append=function(a){this.grids.push(a)};r.prototype.renderGrid=function(a,b){this.provider.layout.width=a.width;this.provider.layout.height=a.height;this.provider.layout.direction=a.direction;this.provider.layout.fontColor=a.fontColor;
this.provider.layout.init();this.provider.parser.context.curFontColor=a.fontColor;a.node.innerHTML=this.provider.outputPage(b).html};r.prototype.appendRestGrid=function(a,b){var c=document.createElement("div");c.innerHTML=this.provider.outputPage(b).html;c.className="nehan-rest-grid";a.node.appendChild(c)};r.prototype.render=function(){for(var a=0;a<this.grids.length;a++){var b=this.grids[a];if(!this.provider.hasNextPage())break;this.renderGrid(b,a);if(b.isEnd)return}b=this.grids[a-1];for(b.node.style.height=
"auto";this.provider.hasNextPage();)this.appendRestGrid(b,a++)};Nehan.Util=g;Nehan.Env=p;Nehan.Layout=o;Nehan.TextStream=l;Nehan.StreamLexer=n;Nehan.StreamParser=e;Nehan.PageProvider=i;Nehan.ParserProxy=k;Nehan.LayoutMapper={start:function(a){for(var a=a||{},b={},c=document.getElementsByTagName("pre"),d=0;d<c.length;d++){var e=c[d],f=e.className;if(f.match(/lp-vertical/i)||f.match(/lp-horizontal/i))e=new s(e,d),b[e.groupName]||(b[e.groupName]=new r(e.groupName,a)),b[e.groupName].append(e)}for(groupName in b)b[groupName].init().render()}}})();
